// Decompiled with JetBrains decompiler
// Type: Microsoft.VisualStudio.Services.Profile.Avatar
// Assembly: Microsoft.VisualStudio.Services.WebApi, Version=19.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 7B264323-C592-4F23-AB6B-55AEDC85864F
// Assembly location: C:\Program Files\Azure DevOps Server 2022\Application Tier\Web Services\bin\Plugins\Microsoft.VisualStudio.Services.WebApi.dll

using System;
using System.Runtime.Serialization;

namespace Microsoft.VisualStudio.Services.Profile
{
  [DataContract]
  public class Avatar : ITimeStamped, ICloneable
  {
    [DataMember]
    public byte[] Value { get; set; }

    [DataMember(IsRequired = false, EmitDefaultValue = false)]
    public DateTimeOffset TimeStamp { get; set; }

    [DataMember(IsRequired = false, EmitDefaultValue = false)]
    public AvatarSize Size { get; internal set; }

    [DataMember(IsRequired = false, EmitDefaultValue = false)]
    public bool? IsAutoGenerated { get; internal set; }

    public object Clone()
    {
      Avatar avatar = new Avatar()
      {
        Size = this.Size,
        TimeStamp = this.TimeStamp,
        IsAutoGenerated = this.IsAutoGenerated
      };
      if (this.Value != null)
      {
        avatar.Value = new byte[this.Value.Length];
        Buffer.BlockCopy((Array) this.Value, 0, (Array) avatar.Value, 0, this.Value.Length);
      }
      return (object) avatar;
    }
  }
}
