// Decompiled with JetBrains decompiler
// Type: Microsoft.VisualStudio.Services.Search.Common.Enums.ProgrammingLanguages
// Assembly: Microsoft.VisualStudio.Services.Search.Common, Version=19.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 8E09DCBA-148E-4EB7-BB73-B53B030BE93E
// Assembly location: C:\Program Files\Azure DevOps Server 2022\Application Tier\Web Services\bin\Plugins\Microsoft.VisualStudio.Services.Search.Common.dll

using Microsoft.VisualStudio.Services.Search.Common.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace Microsoft.VisualStudio.Services.Search.Common.Enums
{
  internal static class ProgrammingLanguages
  {
    private static readonly IDictionary<string, ProgrammingLanguages.ProgrammingLanguage> s_extToLanguageNames = (IDictionary<string, ProgrammingLanguages.ProgrammingLanguage>) new FriendlyDictionary<string, ProgrammingLanguages.ProgrammingLanguage>()
    {
      {
        ".4th",
        ProgrammingLanguages.ProgrammingLanguage.Forth
      },
      {
        ".6pl",
        ProgrammingLanguages.ProgrammingLanguage.Perl6
      },
      {
        ".6pm",
        ProgrammingLanguages.ProgrammingLanguage.Perl6
      },
      {
        ".8xk",
        ProgrammingLanguages.ProgrammingLanguage.TIProgram
      },
      {
        ".8xp",
        ProgrammingLanguages.ProgrammingLanguage.TIProgram
      },
      {
        "._coffee",
        ProgrammingLanguages.ProgrammingLanguage.CoffeeScript
      },
      {
        "._js",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        "._ls",
        ProgrammingLanguages.ProgrammingLanguage.LiveScript
      },
      {
        ".a51",
        ProgrammingLanguages.ProgrammingLanguage.Assembly
      },
      {
        ".abap",
        ProgrammingLanguages.ProgrammingLanguage.ABAP
      },
      {
        ".ada",
        ProgrammingLanguages.ProgrammingLanguage.Ada
      },
      {
        ".adb",
        ProgrammingLanguages.ProgrammingLanguage.Ada
      },
      {
        ".ado",
        ProgrammingLanguages.ProgrammingLanguage.Stata
      },
      {
        ".adp",
        ProgrammingLanguages.ProgrammingLanguage.Tcl
      },
      {
        ".ads",
        ProgrammingLanguages.ProgrammingLanguage.Ada
      },
      {
        ".agc",
        ProgrammingLanguages.ProgrammingLanguage.ApolloGuidanceComputer
      },
      {
        ".agda",
        ProgrammingLanguages.ProgrammingLanguage.Agda
      },
      {
        ".ahk",
        ProgrammingLanguages.ProgrammingLanguage.AutoHotkey
      },
      {
        ".ahkl",
        ProgrammingLanguages.ProgrammingLanguage.AutoHotkey
      },
      {
        ".aj",
        ProgrammingLanguages.ProgrammingLanguage.AspectJ
      },
      {
        ".al",
        ProgrammingLanguages.ProgrammingLanguage.AL
      },
      {
        ".als",
        ProgrammingLanguages.ProgrammingLanguage.Alloy
      },
      {
        ".ampl",
        ProgrammingLanguages.ProgrammingLanguage.AMPL
      },
      {
        ".apl",
        ProgrammingLanguages.ProgrammingLanguage.APL
      },
      {
        ".applescript",
        ProgrammingLanguages.ProgrammingLanguage.AppleScript
      },
      {
        ".arc",
        ProgrammingLanguages.ProgrammingLanguage.Arc
      },
      {
        ".as",
        ProgrammingLanguages.ProgrammingLanguage.ActionScript
      },
      {
        ".asax",
        ProgrammingLanguages.ProgrammingLanguage.ASPDotNET
      },
      {
        ".asc",
        ProgrammingLanguages.ProgrammingLanguage.AGSScript
      },
      {
        ".ascx",
        ProgrammingLanguages.ProgrammingLanguage.ASPDotNET
      },
      {
        ".asd",
        ProgrammingLanguages.ProgrammingLanguage.CommonLisp
      },
      {
        ".ash",
        ProgrammingLanguages.ProgrammingLanguage.AGSScript
      },
      {
        ".ashx",
        ProgrammingLanguages.ProgrammingLanguage.ASPDotNET
      },
      {
        ".asm",
        ProgrammingLanguages.ProgrammingLanguage.Assembly
      },
      {
        ".asmx",
        ProgrammingLanguages.ProgrammingLanguage.ASPDotNET
      },
      {
        ".asp",
        ProgrammingLanguages.ProgrammingLanguage.ASP
      },
      {
        ".aspx",
        ProgrammingLanguages.ProgrammingLanguage.ASPDotNET
      },
      {
        ".au3",
        ProgrammingLanguages.ProgrammingLanguage.AutoIt
      },
      {
        ".aug",
        ProgrammingLanguages.ProgrammingLanguage.Augeas
      },
      {
        ".auk",
        ProgrammingLanguages.ProgrammingLanguage.Awk
      },
      {
        ".aw",
        ProgrammingLanguages.ProgrammingLanguage.PHP
      },
      {
        ".awk",
        ProgrammingLanguages.ProgrammingLanguage.Awk
      },
      {
        ".axd",
        ProgrammingLanguages.ProgrammingLanguage.ASPDotNET
      },
      {
        ".axi",
        ProgrammingLanguages.ProgrammingLanguage.NetLinx
      },
      {
        ".axs",
        ProgrammingLanguages.ProgrammingLanguage.NetLinx
      },
      {
        ".b",
        ProgrammingLanguages.ProgrammingLanguage.Brainfuck
      },
      {
        ".bas",
        ProgrammingLanguages.ProgrammingLanguage.VisualBasic
      },
      {
        ".bash",
        ProgrammingLanguages.ProgrammingLanguage.Shell
      },
      {
        ".bat",
        ProgrammingLanguages.ProgrammingLanguage.Batchfile
      },
      {
        ".bats",
        ProgrammingLanguages.ProgrammingLanguage.Shell
      },
      {
        ".bb",
        ProgrammingLanguages.ProgrammingLanguage.BitBake
      },
      {
        ".bdy",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".befunge",
        ProgrammingLanguages.ProgrammingLanguage.Befunge
      },
      {
        ".bf",
        ProgrammingLanguages.ProgrammingLanguage.Brainfuck
      },
      {
        ".bison",
        ProgrammingLanguages.ProgrammingLanguage.Bison
      },
      {
        ".bmx",
        ProgrammingLanguages.ProgrammingLanguage.BlitzMax
      },
      {
        ".bones",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".boo",
        ProgrammingLanguages.ProgrammingLanguage.Boo
      },
      {
        ".boot",
        ProgrammingLanguages.ProgrammingLanguage.Clojure
      },
      {
        ".bro",
        ProgrammingLanguages.ProgrammingLanguage.Bro
      },
      {
        ".brs",
        ProgrammingLanguages.ProgrammingLanguage.Brightscript
      },
      {
        ".bsl",
        ProgrammingLanguages.ProgrammingLanguage.CEnterprise
      },
      {
        ".bsv",
        ProgrammingLanguages.ProgrammingLanguage.Bluespec
      },
      {
        ".builder",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".bzl",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".c",
        ProgrammingLanguages.ProgrammingLanguage.C
      },
      {
        ".c++",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".cake",
        ProgrammingLanguages.ProgrammingLanguage.CoffeeScript
      },
      {
        ".capnp",
        ProgrammingLanguages.ProgrammingLanguage.CapNProto
      },
      {
        ".cats",
        ProgrammingLanguages.ProgrammingLanguage.C
      },
      {
        ".cbl",
        ProgrammingLanguages.ProgrammingLanguage.COBOL
      },
      {
        ".cc",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".ccp",
        ProgrammingLanguages.ProgrammingLanguage.COBOL
      },
      {
        ".cdf",
        ProgrammingLanguages.ProgrammingLanguage.Mathematica
      },
      {
        ".ceylon",
        ProgrammingLanguages.ProgrammingLanguage.Ceylon
      },
      {
        ".cfc",
        ProgrammingLanguages.ProgrammingLanguage.ColdFusion
      },
      {
        ".cfm",
        ProgrammingLanguages.ProgrammingLanguage.ColdFusion
      },
      {
        ".cfml",
        ProgrammingLanguages.ProgrammingLanguage.ColdFusion
      },
      {
        ".cgi",
        ProgrammingLanguages.ProgrammingLanguage.Perl
      },
      {
        ".cginc",
        ProgrammingLanguages.ProgrammingLanguage.HLSL
      },
      {
        ".ch",
        ProgrammingLanguages.ProgrammingLanguage.Charity
      },
      {
        ".chpl",
        ProgrammingLanguages.ProgrammingLanguage.Chapel
      },
      {
        ".chs",
        ProgrammingLanguages.ProgrammingLanguage.C2hsHaskell
      },
      {
        ".cirru",
        ProgrammingLanguages.ProgrammingLanguage.Cirru
      },
      {
        ".cjsx",
        ProgrammingLanguages.ProgrammingLanguage.CoffeeScript
      },
      {
        ".ck",
        ProgrammingLanguages.ProgrammingLanguage.ChucK
      },
      {
        ".cl",
        ProgrammingLanguages.ProgrammingLanguage.CommonLisp
      },
      {
        ".cl2",
        ProgrammingLanguages.ProgrammingLanguage.Clojure
      },
      {
        ".click",
        ProgrammingLanguages.ProgrammingLanguage.Click
      },
      {
        ".clj",
        ProgrammingLanguages.ProgrammingLanguage.Clojure
      },
      {
        ".cljc",
        ProgrammingLanguages.ProgrammingLanguage.Clojure
      },
      {
        ".cljs",
        ProgrammingLanguages.ProgrammingLanguage.Clojure
      },
      {
        ".cljscm",
        ProgrammingLanguages.ProgrammingLanguage.Clojure
      },
      {
        ".cljx",
        ProgrammingLanguages.ProgrammingLanguage.Clojure
      },
      {
        ".clp",
        ProgrammingLanguages.ProgrammingLanguage.CLIPS
      },
      {
        ".cls",
        ProgrammingLanguages.ProgrammingLanguage.VisualBasic
      },
      {
        ".clw",
        ProgrammingLanguages.ProgrammingLanguage.Clarion
      },
      {
        ".cmake",
        ProgrammingLanguages.ProgrammingLanguage.CMake
      },
      {
        ".cmd",
        ProgrammingLanguages.ProgrammingLanguage.Batchfile
      },
      {
        ".cob",
        ProgrammingLanguages.ProgrammingLanguage.COBOL
      },
      {
        ".cobol",
        ProgrammingLanguages.ProgrammingLanguage.COBOL
      },
      {
        ".coffee",
        ProgrammingLanguages.ProgrammingLanguage.CoffeeScript
      },
      {
        ".com",
        ProgrammingLanguages.ProgrammingLanguage.DIGITALCommandLanguage
      },
      {
        ".command",
        ProgrammingLanguages.ProgrammingLanguage.Shell
      },
      {
        ".coq",
        ProgrammingLanguages.ProgrammingLanguage.Coq
      },
      {
        ".cp",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".cpp",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".cps",
        ProgrammingLanguages.ProgrammingLanguage.ComponentPascal
      },
      {
        ".cpy",
        ProgrammingLanguages.ProgrammingLanguage.COBOL
      },
      {
        ".cr",
        ProgrammingLanguages.ProgrammingLanguage.Crystal
      },
      {
        ".cs",
        ProgrammingLanguages.ProgrammingLanguage.CSharp
      },
      {
        ".csd",
        ProgrammingLanguages.ProgrammingLanguage.CsoundDocument
      },
      {
        ".csh",
        ProgrammingLanguages.ProgrammingLanguage.Tcsh
      },
      {
        ".cshtml",
        ProgrammingLanguages.ProgrammingLanguage.CSharp
      },
      {
        ".csx",
        ProgrammingLanguages.ProgrammingLanguage.CSharp
      },
      {
        ".ctp",
        ProgrammingLanguages.ProgrammingLanguage.PHP
      },
      {
        ".cu",
        ProgrammingLanguages.ProgrammingLanguage.Cuda
      },
      {
        ".cuh",
        ProgrammingLanguages.ProgrammingLanguage.Cuda
      },
      {
        ".cw",
        ProgrammingLanguages.ProgrammingLanguage.Redcode
      },
      {
        ".cxx",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".cy",
        ProgrammingLanguages.ProgrammingLanguage.Cycript
      },
      {
        ".d",
        ProgrammingLanguages.ProgrammingLanguage.D
      },
      {
        ".dart",
        ProgrammingLanguages.ProgrammingLanguage.Dart
      },
      {
        ".dats",
        ProgrammingLanguages.ProgrammingLanguage.ATS
      },
      {
        ".db2",
        ProgrammingLanguages.ProgrammingLanguage.SQLPL
      },
      {
        ".dcl",
        ProgrammingLanguages.ProgrammingLanguage.Clean
      },
      {
        ".ddl",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".decls",
        ProgrammingLanguages.ProgrammingLanguage.BlitzBasic
      },
      {
        ".dfm",
        ProgrammingLanguages.ProgrammingLanguage.Pascal
      },
      {
        ".di",
        ProgrammingLanguages.ProgrammingLanguage.D
      },
      {
        ".djs",
        ProgrammingLanguages.ProgrammingLanguage.Dogescript
      },
      {
        ".dlm",
        ProgrammingLanguages.ProgrammingLanguage.IDL
      },
      {
        ".dm",
        ProgrammingLanguages.ProgrammingLanguage.DM
      },
      {
        ".do",
        ProgrammingLanguages.ProgrammingLanguage.Stata
      },
      {
        ".doh",
        ProgrammingLanguages.ProgrammingLanguage.Stata
      },
      {
        ".dpr",
        ProgrammingLanguages.ProgrammingLanguage.Pascal
      },
      {
        ".druby",
        ProgrammingLanguages.ProgrammingLanguage.Mirah
      },
      {
        ".duby",
        ProgrammingLanguages.ProgrammingLanguage.Mirah
      },
      {
        ".dyalog",
        ProgrammingLanguages.ProgrammingLanguage.APL
      },
      {
        ".dyl",
        ProgrammingLanguages.ProgrammingLanguage.Dylan
      },
      {
        ".dylan",
        ProgrammingLanguages.ProgrammingLanguage.Dylan
      },
      {
        ".e",
        ProgrammingLanguages.ProgrammingLanguage.E
      },
      {
        ".ebuild",
        ProgrammingLanguages.ProgrammingLanguage.GentooEbuild
      },
      {
        ".ec",
        ProgrammingLanguages.ProgrammingLanguage.eC
      },
      {
        ".ecl",
        ProgrammingLanguages.ProgrammingLanguage.ECL
      },
      {
        ".eclass",
        ProgrammingLanguages.ProgrammingLanguage.GentooEclass
      },
      {
        ".eclxml",
        ProgrammingLanguages.ProgrammingLanguage.ECL
      },
      {
        ".eh",
        ProgrammingLanguages.ProgrammingLanguage.eC
      },
      {
        ".el",
        ProgrammingLanguages.ProgrammingLanguage.EmacsLisp
      },
      {
        ".eliom",
        ProgrammingLanguages.ProgrammingLanguage.OCaml
      },
      {
        ".eliomi",
        ProgrammingLanguages.ProgrammingLanguage.OCaml
      },
      {
        ".elm",
        ProgrammingLanguages.ProgrammingLanguage.Elm
      },
      {
        ".em",
        ProgrammingLanguages.ProgrammingLanguage.EmberScript
      },
      {
        ".emacs",
        ProgrammingLanguages.ProgrammingLanguage.EmacsLisp
      },
      {
        ".emberscript",
        ProgrammingLanguages.ProgrammingLanguage.EmberScript
      },
      {
        ".eq",
        ProgrammingLanguages.ProgrammingLanguage.EQ
      },
      {
        ".erl",
        ProgrammingLanguages.ProgrammingLanguage.Erlang
      },
      {
        ".es",
        ProgrammingLanguages.ProgrammingLanguage.Erlang
      },
      {
        ".es6",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".escript",
        ProgrammingLanguages.ProgrammingLanguage.Erlang
      },
      {
        ".ex",
        ProgrammingLanguages.ProgrammingLanguage.Elixir
      },
      {
        ".exs",
        ProgrammingLanguages.ProgrammingLanguage.Elixir
      },
      {
        ".eye",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".f",
        ProgrammingLanguages.ProgrammingLanguage.Fortran
      },
      {
        ".f03",
        ProgrammingLanguages.ProgrammingLanguage.Fortran
      },
      {
        ".f08",
        ProgrammingLanguages.ProgrammingLanguage.Fortran
      },
      {
        ".f77",
        ProgrammingLanguages.ProgrammingLanguage.Fortran
      },
      {
        ".f90",
        ProgrammingLanguages.ProgrammingLanguage.Fortran
      },
      {
        ".f95",
        ProgrammingLanguages.ProgrammingLanguage.Fortran
      },
      {
        ".factor",
        ProgrammingLanguages.ProgrammingLanguage.Factor
      },
      {
        ".fan",
        ProgrammingLanguages.ProgrammingLanguage.Fantom
      },
      {
        ".fancypack",
        ProgrammingLanguages.ProgrammingLanguage.Fancy
      },
      {
        ".fcgi",
        ProgrammingLanguages.ProgrammingLanguage.Lua
      },
      {
        ".feature",
        ProgrammingLanguages.ProgrammingLanguage.Gherkin
      },
      {
        ".fish",
        ProgrammingLanguages.ProgrammingLanguage.fish
      },
      {
        ".flex",
        ProgrammingLanguages.ProgrammingLanguage.JFlex
      },
      {
        ".flux",
        ProgrammingLanguages.ProgrammingLanguage.FLUX
      },
      {
        ".fnc",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".for",
        ProgrammingLanguages.ProgrammingLanguage.Fortran
      },
      {
        ".forth",
        ProgrammingLanguages.ProgrammingLanguage.Forth
      },
      {
        ".fp",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".fpp",
        ProgrammingLanguages.ProgrammingLanguage.Fortran
      },
      {
        ".fr",
        ProgrammingLanguages.ProgrammingLanguage.Forth
      },
      {
        ".frag",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".frg",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".frm",
        ProgrammingLanguages.ProgrammingLanguage.VisualBasic
      },
      {
        ".frt",
        ProgrammingLanguages.ProgrammingLanguage.Forth
      },
      {
        ".frx",
        ProgrammingLanguages.ProgrammingLanguage.VisualBasic
      },
      {
        ".fs",
        ProgrammingLanguages.ProgrammingLanguage.FSharp
      },
      {
        ".fsh",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".fshader",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".fsi",
        ProgrammingLanguages.ProgrammingLanguage.FSharp
      },
      {
        ".fsx",
        ProgrammingLanguages.ProgrammingLanguage.FSharp
      },
      {
        ".fth",
        ProgrammingLanguages.ProgrammingLanguage.Forth
      },
      {
        ".ftl",
        ProgrammingLanguages.ProgrammingLanguage.FreeMarker
      },
      {
        ".fun",
        ProgrammingLanguages.ProgrammingLanguage.StandardML
      },
      {
        ".fx",
        ProgrammingLanguages.ProgrammingLanguage.FLUX
      },
      {
        ".fxh",
        ProgrammingLanguages.ProgrammingLanguage.HLSL
      },
      {
        ".fy",
        ProgrammingLanguages.ProgrammingLanguage.Fancy
      },
      {
        ".g",
        ProgrammingLanguages.ProgrammingLanguage.GAP
      },
      {
        ".g4",
        ProgrammingLanguages.ProgrammingLanguage.ANTLR
      },
      {
        ".gap",
        ProgrammingLanguages.ProgrammingLanguage.GAP
      },
      {
        ".gawk",
        ProgrammingLanguages.ProgrammingLanguage.Awk
      },
      {
        ".gd",
        ProgrammingLanguages.ProgrammingLanguage.GAP
      },
      {
        ".gdb",
        ProgrammingLanguages.ProgrammingLanguage.GDB
      },
      {
        ".gdbinit",
        ProgrammingLanguages.ProgrammingLanguage.GDB
      },
      {
        ".gemspec",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".geo",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".geom",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".gf",
        ProgrammingLanguages.ProgrammingLanguage.GrammaticalFramework
      },
      {
        ".gi",
        ProgrammingLanguages.ProgrammingLanguage.GAP
      },
      {
        ".glf",
        ProgrammingLanguages.ProgrammingLanguage.Glyph
      },
      {
        ".glsl",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".glslv",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".gml",
        ProgrammingLanguages.ProgrammingLanguage.GameMakerLanguage
      },
      {
        ".gms",
        ProgrammingLanguages.ProgrammingLanguage.GAMS
      },
      {
        ".gnu",
        ProgrammingLanguages.ProgrammingLanguage.Gnuplot
      },
      {
        ".gnuplot",
        ProgrammingLanguages.ProgrammingLanguage.Gnuplot
      },
      {
        ".go",
        ProgrammingLanguages.ProgrammingLanguage.Go
      },
      {
        ".god",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".golo",
        ProgrammingLanguages.ProgrammingLanguage.Golo
      },
      {
        ".gp",
        ProgrammingLanguages.ProgrammingLanguage.Gnuplot
      },
      {
        ".grace",
        ProgrammingLanguages.ProgrammingLanguage.Grace
      },
      {
        ".groovy",
        ProgrammingLanguages.ProgrammingLanguage.Groovy
      },
      {
        ".grt",
        ProgrammingLanguages.ProgrammingLanguage.Groovy
      },
      {
        ".gs",
        ProgrammingLanguages.ProgrammingLanguage.Genie
      },
      {
        ".gshader",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".gsp",
        ProgrammingLanguages.ProgrammingLanguage.GroovyServerPages
      },
      {
        ".gst",
        ProgrammingLanguages.ProgrammingLanguage.Gosu
      },
      {
        ".gsx",
        ProgrammingLanguages.ProgrammingLanguage.Gosu
      },
      {
        ".gtpl",
        ProgrammingLanguages.ProgrammingLanguage.Groovy
      },
      {
        ".gvy",
        ProgrammingLanguages.ProgrammingLanguage.Groovy
      },
      {
        ".gyp",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".gypi",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".h",
        ProgrammingLanguages.ProgrammingLanguage.C
      },
      {
        ".h++",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".hats",
        ProgrammingLanguages.ProgrammingLanguage.ATS
      },
      {
        ".hb",
        ProgrammingLanguages.ProgrammingLanguage.Harbour
      },
      {
        ".hcl",
        ProgrammingLanguages.ProgrammingLanguage.HCL
      },
      {
        ".hh",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".hic",
        ProgrammingLanguages.ProgrammingLanguage.Clojure
      },
      {
        ".hlean",
        ProgrammingLanguages.ProgrammingLanguage.Lean
      },
      {
        ".hlsl",
        ProgrammingLanguages.ProgrammingLanguage.HLSL
      },
      {
        ".hlsli",
        ProgrammingLanguages.ProgrammingLanguage.HLSL
      },
      {
        ".hpp",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".hqf",
        ProgrammingLanguages.ProgrammingLanguage.SQF
      },
      {
        ".hrl",
        ProgrammingLanguages.ProgrammingLanguage.Erlang
      },
      {
        ".hs",
        ProgrammingLanguages.ProgrammingLanguage.Haskell
      },
      {
        ".hsc",
        ProgrammingLanguages.ProgrammingLanguage.Haskell
      },
      {
        ".hx",
        ProgrammingLanguages.ProgrammingLanguage.Haxe
      },
      {
        ".hxsl",
        ProgrammingLanguages.ProgrammingLanguage.Haxe
      },
      {
        ".hxx",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".hy",
        ProgrammingLanguages.ProgrammingLanguage.Hy
      },
      {
        ".i7x",
        ProgrammingLanguages.ProgrammingLanguage.Inform7
      },
      {
        ".iced",
        ProgrammingLanguages.ProgrammingLanguage.CoffeeScript
      },
      {
        ".icl",
        ProgrammingLanguages.ProgrammingLanguage.Clean
      },
      {
        ".idc",
        ProgrammingLanguages.ProgrammingLanguage.C
      },
      {
        ".idr",
        ProgrammingLanguages.ProgrammingLanguage.Idris
      },
      {
        ".ihlp",
        ProgrammingLanguages.ProgrammingLanguage.Stata
      },
      {
        ".ijs",
        ProgrammingLanguages.ProgrammingLanguage.J
      },
      {
        ".ik",
        ProgrammingLanguages.ProgrammingLanguage.Ioke
      },
      {
        ".ily",
        ProgrammingLanguages.ProgrammingLanguage.LilyPond
      },
      {
        ".inl",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".ino",
        ProgrammingLanguages.ProgrammingLanguage.Arduino
      },
      {
        ".intr",
        ProgrammingLanguages.ProgrammingLanguage.Dylan
      },
      {
        ".io",
        ProgrammingLanguages.ProgrammingLanguage.Io
      },
      {
        ".iol",
        ProgrammingLanguages.ProgrammingLanguage.Jolie
      },
      {
        ".ipf",
        ProgrammingLanguages.ProgrammingLanguage.IGORPro
      },
      {
        ".ipp",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".iss",
        ProgrammingLanguages.ProgrammingLanguage.InnoSetup
      },
      {
        ".j",
        ProgrammingLanguages.ProgrammingLanguage.Jasmin
      },
      {
        ".jake",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".java",
        ProgrammingLanguages.ProgrammingLanguage.Java
      },
      {
        ".jbuilder",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".jflex",
        ProgrammingLanguages.ProgrammingLanguage.JFlex
      },
      {
        ".jison",
        ProgrammingLanguages.ProgrammingLanguage.Jison
      },
      {
        ".jisonlex",
        ProgrammingLanguages.ProgrammingLanguage.JisonLex
      },
      {
        ".jl",
        ProgrammingLanguages.ProgrammingLanguage.Julia
      },
      {
        ".jq",
        ProgrammingLanguages.ProgrammingLanguage.JSONiq
      },
      {
        ".js",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".jsb",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".jscad",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".jsfl",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".jsm",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".jsp",
        ProgrammingLanguages.ProgrammingLanguage.JavaServerPages
      },
      {
        ".jss",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".jsx",
        ProgrammingLanguages.ProgrammingLanguage.JSX
      },
      {
        ".kid",
        ProgrammingLanguages.ProgrammingLanguage.Genshi
      },
      {
        ".krl",
        ProgrammingLanguages.ProgrammingLanguage.KRL
      },
      {
        ".ksh",
        ProgrammingLanguages.ProgrammingLanguage.Shell
      },
      {
        ".kt",
        ProgrammingLanguages.ProgrammingLanguage.Kotlin
      },
      {
        ".ktm",
        ProgrammingLanguages.ProgrammingLanguage.Kotlin
      },
      {
        ".kts",
        ProgrammingLanguages.ProgrammingLanguage.Kotlin
      },
      {
        ".l",
        ProgrammingLanguages.ProgrammingLanguage.CommonLisp
      },
      {
        ".lagda",
        ProgrammingLanguages.ProgrammingLanguage.LiterateAgda
      },
      {
        ".las",
        ProgrammingLanguages.ProgrammingLanguage.Lasso
      },
      {
        ".lasso",
        ProgrammingLanguages.ProgrammingLanguage.Lasso
      },
      {
        ".lasso8",
        ProgrammingLanguages.ProgrammingLanguage.Lasso
      },
      {
        ".lasso9",
        ProgrammingLanguages.ProgrammingLanguage.Lasso
      },
      {
        ".ldml",
        ProgrammingLanguages.ProgrammingLanguage.Lasso
      },
      {
        ".lean",
        ProgrammingLanguages.ProgrammingLanguage.Lean
      },
      {
        ".lex",
        ProgrammingLanguages.ProgrammingLanguage.Lex
      },
      {
        ".lfe",
        ProgrammingLanguages.ProgrammingLanguage.LFE
      },
      {
        ".lgt",
        ProgrammingLanguages.ProgrammingLanguage.Logtalk
      },
      {
        ".lhs",
        ProgrammingLanguages.ProgrammingLanguage.LiterateHaskell
      },
      {
        ".lid",
        ProgrammingLanguages.ProgrammingLanguage.Dylan
      },
      {
        ".lidr",
        ProgrammingLanguages.ProgrammingLanguage.Idris
      },
      {
        ".lisp",
        ProgrammingLanguages.ProgrammingLanguage.CommonLisp
      },
      {
        ".litcoffee",
        ProgrammingLanguages.ProgrammingLanguage.LiterateCoffeeScript
      },
      {
        ".lkml",
        ProgrammingLanguages.ProgrammingLanguage.LookML
      },
      {
        ".ll",
        ProgrammingLanguages.ProgrammingLanguage.LLVM
      },
      {
        ".lmi",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".logtalk",
        ProgrammingLanguages.ProgrammingLanguage.Logtalk
      },
      {
        ".lol",
        ProgrammingLanguages.ProgrammingLanguage.LOLCODE
      },
      {
        ".lookml",
        ProgrammingLanguages.ProgrammingLanguage.LookML
      },
      {
        ".lpr",
        ProgrammingLanguages.ProgrammingLanguage.Pascal
      },
      {
        ".ls",
        ProgrammingLanguages.ProgrammingLanguage.LiveScript
      },
      {
        ".lsl",
        ProgrammingLanguages.ProgrammingLanguage.LSL
      },
      {
        ".lslp",
        ProgrammingLanguages.ProgrammingLanguage.LSL
      },
      {
        ".lsp",
        ProgrammingLanguages.ProgrammingLanguage.CommonLisp
      },
      {
        ".lua",
        ProgrammingLanguages.ProgrammingLanguage.Lua
      },
      {
        ".lvproj",
        ProgrammingLanguages.ProgrammingLanguage.LabVIEW
      },
      {
        ".ly",
        ProgrammingLanguages.ProgrammingLanguage.LilyPond
      },
      {
        ".m",
        ProgrammingLanguages.ProgrammingLanguage.ObjectiveCpp
      },
      {
        ".m4",
        ProgrammingLanguages.ProgrammingLanguage.M4
      },
      {
        ".ma",
        ProgrammingLanguages.ProgrammingLanguage.Mathematica
      },
      {
        ".mak",
        ProgrammingLanguages.ProgrammingLanguage.Makefile
      },
      {
        ".make",
        ProgrammingLanguages.ProgrammingLanguage.Makefile
      },
      {
        ".mako",
        ProgrammingLanguages.ProgrammingLanguage.Mako
      },
      {
        ".mao",
        ProgrammingLanguages.ProgrammingLanguage.Mako
      },
      {
        ".mata",
        ProgrammingLanguages.ProgrammingLanguage.Stata
      },
      {
        ".matah",
        ProgrammingLanguages.ProgrammingLanguage.Stata
      },
      {
        ".mathematica",
        ProgrammingLanguages.ProgrammingLanguage.Mathematica
      },
      {
        ".matlab",
        ProgrammingLanguages.ProgrammingLanguage.Matlab
      },
      {
        ".mawk",
        ProgrammingLanguages.ProgrammingLanguage.Awk
      },
      {
        ".maxhelp",
        ProgrammingLanguages.ProgrammingLanguage.Max
      },
      {
        ".maxpat",
        ProgrammingLanguages.ProgrammingLanguage.Max
      },
      {
        ".maxproj",
        ProgrammingLanguages.ProgrammingLanguage.Max
      },
      {
        ".mcr",
        ProgrammingLanguages.ProgrammingLanguage.MAXScript
      },
      {
        ".metal",
        ProgrammingLanguages.ProgrammingLanguage.Metal
      },
      {
        ".minid",
        ProgrammingLanguages.ProgrammingLanguage.MiniD
      },
      {
        ".mir",
        ProgrammingLanguages.ProgrammingLanguage.Mirah
      },
      {
        ".mirah",
        ProgrammingLanguages.ProgrammingLanguage.Mirah
      },
      {
        ".mk",
        ProgrammingLanguages.ProgrammingLanguage.Makefile
      },
      {
        ".mkfile",
        ProgrammingLanguages.ProgrammingLanguage.Makefile
      },
      {
        ".ml",
        ProgrammingLanguages.ProgrammingLanguage.OCaml
      },
      {
        ".ml4",
        ProgrammingLanguages.ProgrammingLanguage.OCaml
      },
      {
        ".mli",
        ProgrammingLanguages.ProgrammingLanguage.OCaml
      },
      {
        ".mll",
        ProgrammingLanguages.ProgrammingLanguage.OCaml
      },
      {
        ".mly",
        ProgrammingLanguages.ProgrammingLanguage.OCaml
      },
      {
        ".mm",
        ProgrammingLanguages.ProgrammingLanguage.ObjectiveC
      },
      {
        ".mmk",
        ProgrammingLanguages.ProgrammingLanguage.ModuleManagementSystem
      },
      {
        ".mms",
        ProgrammingLanguages.ProgrammingLanguage.ModuleManagementSystem
      },
      {
        ".mod",
        ProgrammingLanguages.ProgrammingLanguage.AMPL
      },
      {
        ".monkey",
        ProgrammingLanguages.ProgrammingLanguage.Monkey
      },
      {
        ".moo",
        ProgrammingLanguages.ProgrammingLanguage.Mercury
      },
      {
        ".moon",
        ProgrammingLanguages.ProgrammingLanguage.MoonScript
      },
      {
        ".mq4",
        ProgrammingLanguages.ProgrammingLanguage.MQL4
      },
      {
        ".mq5",
        ProgrammingLanguages.ProgrammingLanguage.MQL5
      },
      {
        ".mqh",
        ProgrammingLanguages.ProgrammingLanguage.MQL4
      },
      {
        ".ms",
        ProgrammingLanguages.ProgrammingLanguage.MAXScript
      },
      {
        ".mspec",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".mss",
        ProgrammingLanguages.ProgrammingLanguage.CartoCSS
      },
      {
        ".mt",
        ProgrammingLanguages.ProgrammingLanguage.Mathematica
      },
      {
        ".mu",
        ProgrammingLanguages.ProgrammingLanguage.mupad
      },
      {
        ".muf",
        ProgrammingLanguages.ProgrammingLanguage.MUF
      },
      {
        ".mumps",
        ProgrammingLanguages.ProgrammingLanguage.M
      },
      {
        ".mxt",
        ProgrammingLanguages.ProgrammingLanguage.Max
      },
      {
        ".myt",
        ProgrammingLanguages.ProgrammingLanguage.Myghty
      },
      {
        ".n",
        ProgrammingLanguages.ProgrammingLanguage.Nemerle
      },
      {
        ".nasm",
        ProgrammingLanguages.ProgrammingLanguage.Assembly
      },
      {
        ".nawk",
        ProgrammingLanguages.ProgrammingLanguage.Awk
      },
      {
        ".nb",
        ProgrammingLanguages.ProgrammingLanguage.Mathematica
      },
      {
        ".nbp",
        ProgrammingLanguages.ProgrammingLanguage.Mathematica
      },
      {
        ".nc",
        ProgrammingLanguages.ProgrammingLanguage.nesC
      },
      {
        ".ncl",
        ProgrammingLanguages.ProgrammingLanguage.NCL
      },
      {
        ".ni",
        ProgrammingLanguages.ProgrammingLanguage.Inform7
      },
      {
        ".nim",
        ProgrammingLanguages.ProgrammingLanguage.Nim
      },
      {
        ".nimrod",
        ProgrammingLanguages.ProgrammingLanguage.Nim
      },
      {
        ".nit",
        ProgrammingLanguages.ProgrammingLanguage.Nit
      },
      {
        ".nix",
        ProgrammingLanguages.ProgrammingLanguage.Nix
      },
      {
        ".njs",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".nl",
        ProgrammingLanguages.ProgrammingLanguage.NewLisp
      },
      {
        ".nlogo",
        ProgrammingLanguages.ProgrammingLanguage.NetLogo
      },
      {
        ".nqp",
        ProgrammingLanguages.ProgrammingLanguage.Perl6
      },
      {
        ".nse",
        ProgrammingLanguages.ProgrammingLanguage.Lua
      },
      {
        ".nsh",
        ProgrammingLanguages.ProgrammingLanguage.NSIS
      },
      {
        ".nsi",
        ProgrammingLanguages.ProgrammingLanguage.NSIS
      },
      {
        ".nu",
        ProgrammingLanguages.ProgrammingLanguage.Nu
      },
      {
        ".numpy",
        ProgrammingLanguages.ProgrammingLanguage.NumPy
      },
      {
        ".numpyw",
        ProgrammingLanguages.ProgrammingLanguage.NumPy
      },
      {
        ".numsc",
        ProgrammingLanguages.ProgrammingLanguage.NumPy
      },
      {
        ".nut",
        ProgrammingLanguages.ProgrammingLanguage.Squirrel
      },
      {
        ".ny",
        ProgrammingLanguages.ProgrammingLanguage.CommonLisp
      },
      {
        ".ol",
        ProgrammingLanguages.ProgrammingLanguage.Jolie
      },
      {
        ".omgrofl",
        ProgrammingLanguages.ProgrammingLanguage.Omgrofl
      },
      {
        ".ooc",
        ProgrammingLanguages.ProgrammingLanguage.ooc
      },
      {
        ".opa",
        ProgrammingLanguages.ProgrammingLanguage.Opa
      },
      {
        ".opal",
        ProgrammingLanguages.ProgrammingLanguage.Opal
      },
      {
        ".opencl",
        ProgrammingLanguages.ProgrammingLanguage.OpenCL
      },
      {
        ".orc",
        ProgrammingLanguages.ProgrammingLanguage.Csound
      },
      {
        ".os",
        ProgrammingLanguages.ProgrammingLanguage.CEnterprise
      },
      {
        ".ox",
        ProgrammingLanguages.ProgrammingLanguage.Ox
      },
      {
        ".oxh",
        ProgrammingLanguages.ProgrammingLanguage.Ox
      },
      {
        ".oxo",
        ProgrammingLanguages.ProgrammingLanguage.Ox
      },
      {
        ".oxygene",
        ProgrammingLanguages.ProgrammingLanguage.Oxygene
      },
      {
        ".oz",
        ProgrammingLanguages.ProgrammingLanguage.Oz
      },
      {
        ".p",
        ProgrammingLanguages.ProgrammingLanguage.OpenEdgeABL
      },
      {
        ".p4",
        ProgrammingLanguages.ProgrammingLanguage.P4
      },
      {
        ".p6",
        ProgrammingLanguages.ProgrammingLanguage.Perl6
      },
      {
        ".p6l",
        ProgrammingLanguages.ProgrammingLanguage.Perl6
      },
      {
        ".p6m",
        ProgrammingLanguages.ProgrammingLanguage.Perl6
      },
      {
        ".pac",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".pan",
        ProgrammingLanguages.ProgrammingLanguage.Pan
      },
      {
        ".parrot",
        ProgrammingLanguages.ProgrammingLanguage.Parrot
      },
      {
        ".pas",
        ProgrammingLanguages.ProgrammingLanguage.Pascal
      },
      {
        ".pascal",
        ProgrammingLanguages.ProgrammingLanguage.Pascal
      },
      {
        ".pasm",
        ProgrammingLanguages.ProgrammingLanguage.ParrotAssembly
      },
      {
        ".pat",
        ProgrammingLanguages.ProgrammingLanguage.Max
      },
      {
        ".pb",
        ProgrammingLanguages.ProgrammingLanguage.PureBasic
      },
      {
        ".pbi",
        ProgrammingLanguages.ProgrammingLanguage.PureBasic
      },
      {
        ".pbt",
        ProgrammingLanguages.ProgrammingLanguage.PowerBuilder
      },
      {
        ".pck",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".pd_lua",
        ProgrammingLanguages.ProgrammingLanguage.Lua
      },
      {
        ".pde",
        ProgrammingLanguages.ProgrammingLanguage.Processing
      },
      {
        ".pep",
        ProgrammingLanguages.ProgrammingLanguage.Pep8
      },
      {
        ".perl",
        ProgrammingLanguages.ProgrammingLanguage.Perl
      },
      {
        ".ph",
        ProgrammingLanguages.ProgrammingLanguage.Perl
      },
      {
        ".php",
        ProgrammingLanguages.ProgrammingLanguage.PHP
      },
      {
        ".php3",
        ProgrammingLanguages.ProgrammingLanguage.PHP
      },
      {
        ".php4",
        ProgrammingLanguages.ProgrammingLanguage.PHP
      },
      {
        ".php5",
        ProgrammingLanguages.ProgrammingLanguage.PHP
      },
      {
        ".phps",
        ProgrammingLanguages.ProgrammingLanguage.PHP
      },
      {
        ".phpt",
        ProgrammingLanguages.ProgrammingLanguage.PHP
      },
      {
        ".pig",
        ProgrammingLanguages.ProgrammingLanguage.PigLatin
      },
      {
        ".pike",
        ProgrammingLanguages.ProgrammingLanguage.Pike
      },
      {
        ".pir",
        ProgrammingLanguages.ProgrammingLanguage.ParrotInternalRepresentation
      },
      {
        ".pkb",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".pks",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".pl",
        ProgrammingLanguages.ProgrammingLanguage.Perl
      },
      {
        ".pl6",
        ProgrammingLanguages.ProgrammingLanguage.Perl6
      },
      {
        ".plb",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".plot",
        ProgrammingLanguages.ProgrammingLanguage.Gnuplot
      },
      {
        ".pls",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".plsql",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".plt",
        ProgrammingLanguages.ProgrammingLanguage.Gnuplot
      },
      {
        ".pluginspec",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".plx",
        ProgrammingLanguages.ProgrammingLanguage.Perl
      },
      {
        ".pm",
        ProgrammingLanguages.ProgrammingLanguage.Perl
      },
      {
        ".pm6",
        ProgrammingLanguages.ProgrammingLanguage.Perl6
      },
      {
        ".pmod",
        ProgrammingLanguages.ProgrammingLanguage.Pike
      },
      {
        ".pod",
        ProgrammingLanguages.ProgrammingLanguage.Perl
      },
      {
        ".podsl",
        ProgrammingLanguages.ProgrammingLanguage.CommonLisp
      },
      {
        ".podspec",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".pogo",
        ProgrammingLanguages.ProgrammingLanguage.PogoScript
      },
      {
        ".pony",
        ProgrammingLanguages.ProgrammingLanguage.Pony
      },
      {
        ".pp",
        ProgrammingLanguages.ProgrammingLanguage.Pascal
      },
      {
        ".pprx",
        ProgrammingLanguages.ProgrammingLanguage.REXX
      },
      {
        ".prc",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".prg",
        ProgrammingLanguages.ProgrammingLanguage.xBase
      },
      {
        ".pri",
        ProgrammingLanguages.ProgrammingLanguage.QMake
      },
      {
        ".pro",
        ProgrammingLanguages.ProgrammingLanguage.IDL
      },
      {
        ".prolog",
        ProgrammingLanguages.ProgrammingLanguage.Prolog
      },
      {
        ".prw",
        ProgrammingLanguages.ProgrammingLanguage.xBase
      },
      {
        ".ps1",
        ProgrammingLanguages.ProgrammingLanguage.PowerShell
      },
      {
        ".psc",
        ProgrammingLanguages.ProgrammingLanguage.Papyrus
      },
      {
        ".psd1",
        ProgrammingLanguages.ProgrammingLanguage.PowerShell
      },
      {
        ".psgi",
        ProgrammingLanguages.ProgrammingLanguage.Perl
      },
      {
        ".psm1",
        ProgrammingLanguages.ProgrammingLanguage.PowerShell
      },
      {
        ".purs",
        ProgrammingLanguages.ProgrammingLanguage.PureScript
      },
      {
        ".pwn",
        ProgrammingLanguages.ProgrammingLanguage.PAWN
      },
      {
        ".pxd",
        ProgrammingLanguages.ProgrammingLanguage.Cython
      },
      {
        ".pxi",
        ProgrammingLanguages.ProgrammingLanguage.Cython
      },
      {
        ".py",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".py3",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".pyde",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".pyi",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".pyp",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".pyt",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".pyw",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".pyx",
        ProgrammingLanguages.ProgrammingLanguage.Cython
      },
      {
        ".qbs",
        ProgrammingLanguages.ProgrammingLanguage.QML
      },
      {
        ".qml",
        ProgrammingLanguages.ProgrammingLanguage.QML
      },
      {
        ".r",
        ProgrammingLanguages.ProgrammingLanguage.R
      },
      {
        ".r2",
        ProgrammingLanguages.ProgrammingLanguage.Rebol
      },
      {
        ".r3",
        ProgrammingLanguages.ProgrammingLanguage.Rebol
      },
      {
        ".rabl",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".rake",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".rb",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".rbbas",
        ProgrammingLanguages.ProgrammingLanguage.REALbasic
      },
      {
        ".rbfrm",
        ProgrammingLanguages.ProgrammingLanguage.REALbasic
      },
      {
        ".rbmnu",
        ProgrammingLanguages.ProgrammingLanguage.REALbasic
      },
      {
        ".rbres",
        ProgrammingLanguages.ProgrammingLanguage.REALbasic
      },
      {
        ".rbtbar",
        ProgrammingLanguages.ProgrammingLanguage.REALbasic
      },
      {
        ".rbuild",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".rbuistate",
        ProgrammingLanguages.ProgrammingLanguage.REALbasic
      },
      {
        ".rbw",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".rbx",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".rbxs",
        ProgrammingLanguages.ProgrammingLanguage.Lua
      },
      {
        ".rd",
        ProgrammingLanguages.ProgrammingLanguage.R
      },
      {
        ".re",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".reb",
        ProgrammingLanguages.ProgrammingLanguage.Rebol
      },
      {
        ".rebol",
        ProgrammingLanguages.ProgrammingLanguage.Rebol
      },
      {
        ".red",
        ProgrammingLanguages.ProgrammingLanguage.Red
      },
      {
        ".reds",
        ProgrammingLanguages.ProgrammingLanguage.Red
      },
      {
        ".rei",
        ProgrammingLanguages.ProgrammingLanguage.Reason
      },
      {
        ".rex",
        ProgrammingLanguages.ProgrammingLanguage.REXX
      },
      {
        ".rexx",
        ProgrammingLanguages.ProgrammingLanguage.REXX
      },
      {
        ".rg",
        ProgrammingLanguages.ProgrammingLanguage.Rouge
      },
      {
        ".ring",
        ProgrammingLanguages.ProgrammingLanguage.Ring
      },
      {
        ".rkt",
        ProgrammingLanguages.ProgrammingLanguage.Racket
      },
      {
        ".rktd",
        ProgrammingLanguages.ProgrammingLanguage.Racket
      },
      {
        ".rktl",
        ProgrammingLanguages.ProgrammingLanguage.Racket
      },
      {
        ".rl",
        ProgrammingLanguages.ProgrammingLanguage.Ragel
      },
      {
        ".robot",
        ProgrammingLanguages.ProgrammingLanguage.RobotFramework
      },
      {
        ".rpy",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".rs",
        ProgrammingLanguages.ProgrammingLanguage.Rust
      },
      {
        ".rsc",
        ProgrammingLanguages.ProgrammingLanguage.Rascal
      },
      {
        ".rsh",
        ProgrammingLanguages.ProgrammingLanguage.RenderScript
      },
      {
        ".rsx",
        ProgrammingLanguages.ProgrammingLanguage.R
      },
      {
        ".ru",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".ruby",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".s",
        ProgrammingLanguages.ProgrammingLanguage.UnixAssembly
      },
      {
        ".sage",
        ProgrammingLanguages.ProgrammingLanguage.Sage
      },
      {
        ".sagews",
        ProgrammingLanguages.ProgrammingLanguage.Sage
      },
      {
        ".sas",
        ProgrammingLanguages.ProgrammingLanguage.SAS
      },
      {
        ".sats",
        ProgrammingLanguages.ProgrammingLanguage.ATS
      },
      {
        ".sbt",
        ProgrammingLanguages.ProgrammingLanguage.Scala
      },
      {
        ".sc",
        ProgrammingLanguages.ProgrammingLanguage.Scala
      },
      {
        ".scad",
        ProgrammingLanguages.ProgrammingLanguage.OpenSCAD
      },
      {
        ".scala",
        ProgrammingLanguages.ProgrammingLanguage.Scala
      },
      {
        ".scd",
        ProgrammingLanguages.ProgrammingLanguage.SuperCollider
      },
      {
        ".sce",
        ProgrammingLanguages.ProgrammingLanguage.Scilab
      },
      {
        ".sch",
        ProgrammingLanguages.ProgrammingLanguage.Scheme
      },
      {
        ".sci",
        ProgrammingLanguages.ProgrammingLanguage.Scilab
      },
      {
        ".scm",
        ProgrammingLanguages.ProgrammingLanguage.Scheme
      },
      {
        ".sco",
        ProgrammingLanguages.ProgrammingLanguage.CsoundScore
      },
      {
        ".scpt",
        ProgrammingLanguages.ProgrammingLanguage.AppleScript
      },
      {
        ".scrbl",
        ProgrammingLanguages.ProgrammingLanguage.Racket
      },
      {
        ".self",
        ProgrammingLanguages.ProgrammingLanguage.Self
      },
      {
        ".sexp",
        ProgrammingLanguages.ProgrammingLanguage.CommonLisp
      },
      {
        ".sh",
        ProgrammingLanguages.ProgrammingLanguage.Shell
      },
      {
        ".sh-session",
        ProgrammingLanguages.ProgrammingLanguage.ShellSession
      },
      {
        ".shader",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".shen",
        ProgrammingLanguages.ProgrammingLanguage.Shen
      },
      {
        ".sig",
        ProgrammingLanguages.ProgrammingLanguage.StandardML
      },
      {
        ".sj",
        ProgrammingLanguages.ProgrammingLanguage.ObjectiveJ
      },
      {
        ".sjs",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".sl",
        ProgrammingLanguages.ProgrammingLanguage.Slash
      },
      {
        ".sld",
        ProgrammingLanguages.ProgrammingLanguage.Scheme
      },
      {
        ".sls",
        ProgrammingLanguages.ProgrammingLanguage.SaltStack
      },
      {
        ".sma",
        ProgrammingLanguages.ProgrammingLanguage.SourcePawn
      },
      {
        ".smali",
        ProgrammingLanguages.ProgrammingLanguage.Smali
      },
      {
        ".sml",
        ProgrammingLanguages.ProgrammingLanguage.StandardML
      },
      {
        ".smt",
        ProgrammingLanguages.ProgrammingLanguage.SMT
      },
      {
        ".smt2",
        ProgrammingLanguages.ProgrammingLanguage.SMT
      },
      {
        ".sp",
        ProgrammingLanguages.ProgrammingLanguage.SourcePawn
      },
      {
        ".spc",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".spec",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".spin",
        ProgrammingLanguages.ProgrammingLanguage.PropellerSpin
      },
      {
        ".sps",
        ProgrammingLanguages.ProgrammingLanguage.Scheme
      },
      {
        ".sqf",
        ProgrammingLanguages.ProgrammingLanguage.SQF
      },
      {
        ".sql",
        ProgrammingLanguages.ProgrammingLanguage.SQL
      },
      {
        ".sra",
        ProgrammingLanguages.ProgrammingLanguage.PowerBuilder
      },
      {
        ".sru",
        ProgrammingLanguages.ProgrammingLanguage.PowerBuilder
      },
      {
        ".srw",
        ProgrammingLanguages.ProgrammingLanguage.PowerBuilder
      },
      {
        ".ss",
        ProgrammingLanguages.ProgrammingLanguage.Scheme
      },
      {
        ".ssjs",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".st",
        ProgrammingLanguages.ProgrammingLanguage.Smalltalk
      },
      {
        ".stan",
        ProgrammingLanguages.ProgrammingLanguage.Stan
      },
      {
        ".sthlp",
        ProgrammingLanguages.ProgrammingLanguage.Stata
      },
      {
        ".sv",
        ProgrammingLanguages.ProgrammingLanguage.SystemVerilog
      },
      {
        ".svh",
        ProgrammingLanguages.ProgrammingLanguage.SystemVerilog
      },
      {
        ".swift",
        ProgrammingLanguages.ProgrammingLanguage.Swift
      },
      {
        ".t",
        ProgrammingLanguages.ProgrammingLanguage.Perl
      },
      {
        ".tac",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".tcc",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".tcl",
        ProgrammingLanguages.ProgrammingLanguage.Tcl
      },
      {
        ".tcsh",
        ProgrammingLanguages.ProgrammingLanguage.Tcsh
      },
      {
        ".tesc",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".tese",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".tf",
        ProgrammingLanguages.ProgrammingLanguage.HCL
      },
      {
        ".thor",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".thrift",
        ProgrammingLanguages.ProgrammingLanguage.Thrift
      },
      {
        ".thy",
        ProgrammingLanguages.ProgrammingLanguage.Isabelle
      },
      {
        ".tla",
        ProgrammingLanguages.ProgrammingLanguage.TLA
      },
      {
        ".tm",
        ProgrammingLanguages.ProgrammingLanguage.Tcl
      },
      {
        ".tmux",
        ProgrammingLanguages.ProgrammingLanguage.Shell
      },
      {
        ".tool",
        ProgrammingLanguages.ProgrammingLanguage.Shell
      },
      {
        ".tpb",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".tpl",
        ProgrammingLanguages.ProgrammingLanguage.Smarty
      },
      {
        ".tpp",
        ProgrammingLanguages.ProgrammingLanguage.Cpp
      },
      {
        ".tps",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".trg",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".ts",
        ProgrammingLanguages.ProgrammingLanguage.TypeScript
      },
      {
        ".tst",
        ProgrammingLanguages.ProgrammingLanguage.GAP
      },
      {
        ".tsx",
        ProgrammingLanguages.ProgrammingLanguage.TypeScript
      },
      {
        ".tu",
        ProgrammingLanguages.ProgrammingLanguage.Turing
      },
      {
        ".txl",
        ProgrammingLanguages.ProgrammingLanguage.TXL
      },
      {
        ".uc",
        ProgrammingLanguages.ProgrammingLanguage.UnrealScript
      },
      {
        ".udo",
        ProgrammingLanguages.ProgrammingLanguage.Csound
      },
      {
        ".uno",
        ProgrammingLanguages.ProgrammingLanguage.Uno
      },
      {
        ".upc",
        ProgrammingLanguages.ProgrammingLanguage.UnifiedParallelC
      },
      {
        ".ur",
        ProgrammingLanguages.ProgrammingLanguage.UrWeb
      },
      {
        ".urs",
        ProgrammingLanguages.ProgrammingLanguage.UrWeb
      },
      {
        ".v",
        ProgrammingLanguages.ProgrammingLanguage.Coq
      },
      {
        ".vala",
        ProgrammingLanguages.ProgrammingLanguage.Vala
      },
      {
        ".vapi",
        ProgrammingLanguages.ProgrammingLanguage.Vala
      },
      {
        ".vark",
        ProgrammingLanguages.ProgrammingLanguage.Gosu
      },
      {
        ".vb",
        ProgrammingLanguages.ProgrammingLanguage.VisualBasic
      },
      {
        ".vba",
        ProgrammingLanguages.ProgrammingLanguage.VisualBasic
      },
      {
        ".vbhtml",
        ProgrammingLanguages.ProgrammingLanguage.VisualBasic
      },
      {
        ".vbs",
        ProgrammingLanguages.ProgrammingLanguage.VisualBasic
      },
      {
        ".vcl",
        ProgrammingLanguages.ProgrammingLanguage.VCL
      },
      {
        ".veo",
        ProgrammingLanguages.ProgrammingLanguage.Verilog
      },
      {
        ".vert",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".vh",
        ProgrammingLanguages.ProgrammingLanguage.SystemVerilog
      },
      {
        ".vhd",
        ProgrammingLanguages.ProgrammingLanguage.VHDL
      },
      {
        ".vhdl",
        ProgrammingLanguages.ProgrammingLanguage.VHDL
      },
      {
        ".vhf",
        ProgrammingLanguages.ProgrammingLanguage.VHDL
      },
      {
        ".vhi",
        ProgrammingLanguages.ProgrammingLanguage.VHDL
      },
      {
        ".vho",
        ProgrammingLanguages.ProgrammingLanguage.VHDL
      },
      {
        ".vhs",
        ProgrammingLanguages.ProgrammingLanguage.VHDL
      },
      {
        ".vht",
        ProgrammingLanguages.ProgrammingLanguage.VHDL
      },
      {
        ".vhw",
        ProgrammingLanguages.ProgrammingLanguage.VHDL
      },
      {
        ".vim",
        ProgrammingLanguages.ProgrammingLanguage.Vimscript
      },
      {
        ".volt",
        ProgrammingLanguages.ProgrammingLanguage.Volt
      },
      {
        ".vrx",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".vsh",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".vshader",
        ProgrammingLanguages.ProgrammingLanguage.GLSL
      },
      {
        ".vw",
        ProgrammingLanguages.ProgrammingLanguage.PLSQL
      },
      {
        ".w",
        ProgrammingLanguages.ProgrammingLanguage.CWeb
      },
      {
        ".wast",
        ProgrammingLanguages.ProgrammingLanguage.WebAssembly
      },
      {
        ".wat",
        ProgrammingLanguages.ProgrammingLanguage.WebAssembly
      },
      {
        ".watchr",
        ProgrammingLanguages.ProgrammingLanguage.Ruby
      },
      {
        ".webidl",
        ProgrammingLanguages.ProgrammingLanguage.WebIDL
      },
      {
        ".wisp",
        ProgrammingLanguages.ProgrammingLanguage.wisp
      },
      {
        ".wl",
        ProgrammingLanguages.ProgrammingLanguage.Mathematica
      },
      {
        ".wlt",
        ProgrammingLanguages.ProgrammingLanguage.Mathematica
      },
      {
        ".wlua",
        ProgrammingLanguages.ProgrammingLanguage.Lua
      },
      {
        ".wsgi",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".x",
        ProgrammingLanguages.ProgrammingLanguage.Lex
      },
      {
        ".x10",
        ProgrammingLanguages.ProgrammingLanguage.X10
      },
      {
        ".xc",
        ProgrammingLanguages.ProgrammingLanguage.XC
      },
      {
        ".xi",
        ProgrammingLanguages.ProgrammingLanguage.Logos
      },
      {
        ".xm",
        ProgrammingLanguages.ProgrammingLanguage.Logos
      },
      {
        ".xojo_code",
        ProgrammingLanguages.ProgrammingLanguage.Xojo
      },
      {
        ".xojo_menu",
        ProgrammingLanguages.ProgrammingLanguage.Xojo
      },
      {
        ".xojo_report",
        ProgrammingLanguages.ProgrammingLanguage.Xojo
      },
      {
        ".xojo_script",
        ProgrammingLanguages.ProgrammingLanguage.Xojo
      },
      {
        ".xojo_toolbar",
        ProgrammingLanguages.ProgrammingLanguage.Xojo
      },
      {
        ".xojo_window",
        ProgrammingLanguages.ProgrammingLanguage.Xojo
      },
      {
        ".xpl",
        ProgrammingLanguages.ProgrammingLanguage.XProc
      },
      {
        ".xproc",
        ProgrammingLanguages.ProgrammingLanguage.XProc
      },
      {
        ".xpy",
        ProgrammingLanguages.ProgrammingLanguage.Python
      },
      {
        ".xq",
        ProgrammingLanguages.ProgrammingLanguage.XQuery
      },
      {
        ".xql",
        ProgrammingLanguages.ProgrammingLanguage.XQuery
      },
      {
        ".xqm",
        ProgrammingLanguages.ProgrammingLanguage.XQuery
      },
      {
        ".xquery",
        ProgrammingLanguages.ProgrammingLanguage.XQuery
      },
      {
        ".xqy",
        ProgrammingLanguages.ProgrammingLanguage.XQuery
      },
      {
        ".xrl",
        ProgrammingLanguages.ProgrammingLanguage.Erlang
      },
      {
        ".xs",
        ProgrammingLanguages.ProgrammingLanguage.XS
      },
      {
        ".xsjs",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".xsjslib",
        ProgrammingLanguages.ProgrammingLanguage.JavaScript
      },
      {
        ".xsl",
        ProgrammingLanguages.ProgrammingLanguage.XSLT
      },
      {
        ".xslt",
        ProgrammingLanguages.ProgrammingLanguage.XSLT
      },
      {
        ".xtend",
        ProgrammingLanguages.ProgrammingLanguage.Xtend
      },
      {
        ".y",
        ProgrammingLanguages.ProgrammingLanguage.Yacc
      },
      {
        ".yacc",
        ProgrammingLanguages.ProgrammingLanguage.Yacc
      },
      {
        ".yap",
        ProgrammingLanguages.ProgrammingLanguage.Prolog
      },
      {
        ".yrl",
        ProgrammingLanguages.ProgrammingLanguage.Erlang
      },
      {
        ".yy",
        ProgrammingLanguages.ProgrammingLanguage.Yacc
      },
      {
        ".zep",
        ProgrammingLanguages.ProgrammingLanguage.Zephir
      },
      {
        ".zimpl",
        ProgrammingLanguages.ProgrammingLanguage.Zimpl
      },
      {
        ".zmpl",
        ProgrammingLanguages.ProgrammingLanguage.Zimpl
      },
      {
        ".zpl",
        ProgrammingLanguages.ProgrammingLanguage.Zimpl
      },
      {
        ".zsh",
        ProgrammingLanguages.ProgrammingLanguage.Shell
      },
      {
        ".apib",
        ProgrammingLanguages.ProgrammingLanguage.APIBlueprint
      },
      {
        ".blade",
        ProgrammingLanguages.ProgrammingLanguage.Blade
      },
      {
        ".css",
        ProgrammingLanguages.ProgrammingLanguage.CSS
      },
      {
        ".soy",
        ProgrammingLanguages.ProgrammingLanguage.ClosureTemplates
      },
      {
        ".ejs",
        ProgrammingLanguages.ProgrammingLanguage.EJS
      },
      {
        ".html",
        ProgrammingLanguages.ProgrammingLanguage.HTML
      },
      {
        ".htm",
        ProgrammingLanguages.ProgrammingLanguage.HTML
      },
      {
        ".xht",
        ProgrammingLanguages.ProgrammingLanguage.HTML
      },
      {
        ".xhtml",
        ProgrammingLanguages.ProgrammingLanguage.HTML
      },
      {
        ".jinja",
        ProgrammingLanguages.ProgrammingLanguage.HTMLDjango
      },
      {
        ".mustache",
        ProgrammingLanguages.ProgrammingLanguage.HTMLDjango
      },
      {
        ".njk",
        ProgrammingLanguages.ProgrammingLanguage.HTMLDjango
      },
      {
        ".ecr",
        ProgrammingLanguages.ProgrammingLanguage.HTMLECR
      },
      {
        ".eex",
        ProgrammingLanguages.ProgrammingLanguage.HTMLEEX
      },
      {
        ".erb",
        ProgrammingLanguages.ProgrammingLanguage.HTMLERB
      },
      {
        ".phtml",
        ProgrammingLanguages.ProgrammingLanguage.HTMLPHP
      },
      {
        ".haml",
        ProgrammingLanguages.ProgrammingLanguage.Haml
      },
      {
        ".handlebars",
        ProgrammingLanguages.ProgrammingLanguage.Handlebars
      },
      {
        ".hbs",
        ProgrammingLanguages.ProgrammingLanguage.Handlebars
      },
      {
        ".ipynb",
        ProgrammingLanguages.ProgrammingLanguage.JupyterNotebook
      },
      {
        ".kit",
        ProgrammingLanguages.ProgrammingLanguage.Kit
      },
      {
        ".latte",
        ProgrammingLanguages.ProgrammingLanguage.Latte
      },
      {
        ".less",
        ProgrammingLanguages.ProgrammingLanguage.Less
      },
      {
        ".liquid",
        ProgrammingLanguages.ProgrammingLanguage.Liquid
      },
      {
        ".mtml",
        ProgrammingLanguages.ProgrammingLanguage.MTML
      },
      {
        ".marko",
        ProgrammingLanguages.ProgrammingLanguage.Marko
      },
      {
        ".mask",
        ProgrammingLanguages.ProgrammingLanguage.Mask
      },
      {
        ".pic",
        ProgrammingLanguages.ProgrammingLanguage.Pic
      },
      {
        ".chem",
        ProgrammingLanguages.ProgrammingLanguage.Pic
      },
      {
        ".ps",
        ProgrammingLanguages.ProgrammingLanguage.PostScript
      },
      {
        ".eps",
        ProgrammingLanguages.ProgrammingLanguage.PostScript
      },
      {
        ".pfa",
        ProgrammingLanguages.ProgrammingLanguage.PostScript
      },
      {
        ".jade",
        ProgrammingLanguages.ProgrammingLanguage.Pug
      },
      {
        ".pug",
        ProgrammingLanguages.ProgrammingLanguage.Pug
      },
      {
        ".raml",
        ProgrammingLanguages.ProgrammingLanguage.RAML
      },
      {
        ".rhtml",
        ProgrammingLanguages.ProgrammingLanguage.RHTML
      },
      {
        ".rnh",
        ProgrammingLanguages.ProgrammingLanguage.RUNOFF
      },
      {
        ".rno",
        ProgrammingLanguages.ProgrammingLanguage.RUNOFF
      },
      {
        ".scss",
        ProgrammingLanguages.ProgrammingLanguage.SCSS
      },
      {
        ".sass",
        ProgrammingLanguages.ProgrammingLanguage.Sass
      },
      {
        ".scaml",
        ProgrammingLanguages.ProgrammingLanguage.Scaml
      },
      {
        ".slim",
        ProgrammingLanguages.ProgrammingLanguage.Slim
      },
      {
        ".styl",
        ProgrammingLanguages.ProgrammingLanguage.Stylus
      },
      {
        ".tex",
        ProgrammingLanguages.ProgrammingLanguage.TeX
      },
      {
        ".ltx",
        ProgrammingLanguages.ProgrammingLanguage.TeX
      },
      {
        ".mkii",
        ProgrammingLanguages.ProgrammingLanguage.TeX
      },
      {
        ".mkiv",
        ProgrammingLanguages.ProgrammingLanguage.TeX
      },
      {
        ".mkvi",
        ProgrammingLanguages.ProgrammingLanguage.TeX
      },
      {
        ".sty",
        ProgrammingLanguages.ProgrammingLanguage.TeX
      },
      {
        ".tea",
        ProgrammingLanguages.ProgrammingLanguage.Tea
      },
      {
        ".twig",
        ProgrammingLanguages.ProgrammingLanguage.Twig
      },
      {
        ".vue",
        ProgrammingLanguages.ProgrammingLanguage.Vue
      }
    };
    private static readonly IDictionary<ProgrammingLanguages.ProgrammingLanguage, string> s_programmingLanguageToDisplayName = (IDictionary<ProgrammingLanguages.ProgrammingLanguage, string>) Enum.GetValues(typeof (ProgrammingLanguages.ProgrammingLanguage)).Cast<ProgrammingLanguages.ProgrammingLanguage>().ToDictionary<ProgrammingLanguages.ProgrammingLanguage, ProgrammingLanguages.ProgrammingLanguage, string>((Func<ProgrammingLanguages.ProgrammingLanguage, ProgrammingLanguages.ProgrammingLanguage>) (language => language), new Func<ProgrammingLanguages.ProgrammingLanguage, string>(ProgrammingLanguages.GetName));

    public static ProgrammingLanguages.ProgrammingLanguage GetProgrammingLanguage(
      string fileExtensionOrName)
    {
      if (string.IsNullOrWhiteSpace(fileExtensionOrName))
        return ProgrammingLanguages.ProgrammingLanguage.Others;
      fileExtensionOrName = fileExtensionOrName.Contains(".") ? fileExtensionOrName : "." + fileExtensionOrName;
      string lowerInvariant = FilePathUtils.GetFileExtension(fileExtensionOrName).ToLowerInvariant();
      ProgrammingLanguages.ProgrammingLanguage programmingLanguage;
      return ProgrammingLanguages.s_extToLanguageNames.TryGetValue(lowerInvariant, out programmingLanguage) ? programmingLanguage : ProgrammingLanguages.ProgrammingLanguage.Others;
    }

    public static List<string> GetProgrammingLanguageExtensions(
      ProgrammingLanguages.ProgrammingLanguage language)
    {
      List<string> languageExtensions = new List<string>();
      foreach (KeyValuePair<string, ProgrammingLanguages.ProgrammingLanguage> extToLanguageName in (IEnumerable<KeyValuePair<string, ProgrammingLanguages.ProgrammingLanguage>>) ProgrammingLanguages.s_extToLanguageNames)
      {
        if (extToLanguageName.Value == language)
          languageExtensions.Add(extToLanguageName.Key);
      }
      return languageExtensions;
    }

    public static string GetProgrammingLanguageDisplayName(
      this ProgrammingLanguages.ProgrammingLanguage language)
    {
      return ProgrammingLanguages.s_programmingLanguageToDisplayName[language];
    }

    private static string GetName(ProgrammingLanguages.ProgrammingLanguage language) => !(language.GetType().GetField(language.ToString()).GetCustomAttributes(typeof (DescriptionAttribute), false) is DescriptionAttribute[] customAttributes) || customAttributes.Length == 0 ? language.ToString() : customAttributes[0].Description;

    internal enum ProgrammingLanguage
    {
      Others,
      Forth,
      [Description("Perl 6")] Perl6,
      [Description("TI Program")] TIProgram,
      CoffeeScript,
      JavaScript,
      LiveScript,
      Assembly,
      ABAP,
      Ada,
      Stata,
      Tcl,
      [Description("Apollo Guidance Computer")] ApolloGuidanceComputer,
      Agda,
      AutoHotkey,
      AspectJ,
      AL,
      Alloy,
      AMPL,
      APL,
      Erlang,
      AppleScript,
      Arc,
      ActionScript,
      ASPDotNET,
      [Description("AGS Script")] AGSScript,
      [Description("Common Lisp")] CommonLisp,
      ASP,
      AutoIt,
      Augeas,
      Awk,
      PHP,
      NetLinx,
      Brainfuck,
      [Description("Visual Basic")] VisualBasic,
      Shell,
      Batchfile,
      BitBake,
      PLSQL,
      Befunge,
      Bison,
      BlitzMax,
      Boo,
      Clojure,
      Bro,
      Brightscript,
      [Description("1C Enterprise")] CEnterprise,
      Bluespec,
      Ruby,
      Python,
      C,
      Cpp,
      [Description("Cap'n Proto")] CapNProto,
      COBOL,
      Mathematica,
      Ceylon,
      [Description("ColdFusion CFC")] ColdFusionCFC,
      ColdFusion,
      Perl,
      HLSL,
      Charity,
      Chapel,
      [Description("C2hs Haskell")] C2hsHaskell,
      Cirru,
      ChucK,
      Click,
      CLIPS,
      Clarion,
      CMake,
      [Description("DIGITAL Command Language")] DIGITALCommandLanguage,
      Coq,
      [Description("Component Pascal")] ComponentPascal,
      Crystal,
      [Description("C#")] CSharp,
      [Description("Csound Document")] CsoundDocument,
      Tcsh,
      Cuda,
      Redcode,
      Cycript,
      D,
      Dart,
      ATS,
      SQLPL,
      Clean,
      BlitzBasic,
      Pascal,
      Dogescript,
      IDL,
      DM,
      Mirah,
      Dylan,
      E,
      [Description("Gentoo Ebuild")] GentooEbuild,
      eC,
      ECL,
      [Description("Gentoo Eclass")] GentooEclass,
      [Description("Emacs Lisp")] EmacsLisp,
      OCaml,
      Elm,
      EmberScript,
      EQ,
      Elixir,
      Fortran,
      Factor,
      Fantom,
      Fancy,
      Lua,
      Gherkin,
      fish,
      JFlex,
      FLUX,
      GLSL,
      [Description("F#")] FSharp,
      FreeMarker,
      [Description("Standard ML")] StandardML,
      GAP,
      ANTLR,
      GDB,
      [Description("Grammatical Framework")] GrammaticalFramework,
      Glyph,
      [Description("Game Maker Language")] GameMakerLanguage,
      GAMS,
      Gnuplot,
      Go,
      Golo,
      Grace,
      Groovy,
      Genie,
      [Description("Groovy Server Pages")] GroovyServerPages,
      Gosu,
      Harbour,
      HCL,
      Lean,
      SQF,
      Haskell,
      Haxe,
      Hy,
      [Description("Inform 7")] Inform7,
      Idris,
      J,
      Ioke,
      LilyPond,
      Arduino,
      Io,
      Jolie,
      [Description("IGOR Pro")] IGORPro,
      [Description("Inno Setup")] InnoSetup,
      Jasmin,
      Java,
      Jison,
      [Description("Jison Lex")] JisonLex,
      Julia,
      JSONiq,
      [Description("Java Server Pages")] JavaServerPages,
      JSX,
      Genshi,
      KRL,
      Kotlin,
      [Description("Literate Agda")] LiterateAgda,
      Lasso,
      Lex,
      LFE,
      Logtalk,
      [Description("Literate Haskell")] LiterateHaskell,
      [Description("Literate Coffee Script")] LiterateCoffeeScript,
      LookML,
      LLVM,
      LOLCODE,
      LSL,
      LabVIEW,
      [Description("Objective-C")] ObjectiveC,
      M4,
      Makefile,
      Mako,
      Matlab,
      Max,
      MAXScript,
      Metal,
      MiniD,
      [Description("Objective-Cpp")] ObjectiveCpp,
      [Description("Module Management System")] ModuleManagementSystem,
      Monkey,
      Mercury,
      MoonScript,
      MQL4,
      MQL5,
      CartoCSS,
      mupad,
      MUF,
      M,
      Myghty,
      Nemerle,
      nesC,
      NCL,
      Nim,
      Nit,
      Nix,
      NewLisp,
      NetLogo,
      NSIS,
      Nu,
      NumPy,
      Squirrel,
      Omgrofl,
      ooc,
      Opa,
      Opal,
      OpenCL,
      Csound,
      Ox,
      Oxygene,
      Oz,
      [Description("Open Edge ABL")] OpenEdgeABL,
      P4,
      Pan,
      Parrot,
      [Description("Parrot Assembly")] ParrotAssembly,
      PureBasic,
      PowerBuilder,
      Processing,
      Pep8,
      PigLatin,
      Pike,
      [Description("Parrot Internal Representation")] ParrotInternalRepresentation,
      PogoScript,
      Pony,
      [Description("POV-Ray SDL")] POVRaySDL,
      REXX,
      xBase,
      QMake,
      Prolog,
      PowerShell,
      Papyrus,
      PureScript,
      PAWN,
      Cython,
      QML,
      R,
      Rebol,
      REALbasic,
      Red,
      Reason,
      Rouge,
      Ring,
      Racket,
      Ragel,
      RobotFramework,
      Rust,
      Rascal,
      RenderScript,
      [Description("Unix Assembly")] UnixAssembly,
      Sage,
      SAS,
      Scala,
      OpenSCAD,
      SuperCollider,
      Scilab,
      Scheme,
      CsoundScore,
      Self,
      ShellSession,
      Shen,
      [Description("Objective-J")] ObjectiveJ,
      Slash,
      SaltStack,
      SourcePawn,
      Smali,
      SMT,
      PropellerSpin,
      SQL,
      Smalltalk,
      Stan,
      SystemVerilog,
      Swift,
      Thrift,
      Isabelle,
      TLA,
      Smarty,
      TypeScript,
      Turing,
      TXL,
      UnrealScript,
      Uno,
      [Description("Unified Parallel C")] UnifiedParallelC,
      UrWeb,
      Vala,
      VCL,
      Verilog,
      VHDL,
      [Description("Vim script")] Vimscript,
      Volt,
      CWeb,
      WebAssembly,
      WebIDL,
      wisp,
      Logos,
      X10,
      XC,
      Xojo,
      XProc,
      XQuery,
      XS,
      XSLT,
      Xtend,
      Yacc,
      Zephir,
      Zimpl,
      [Description("API Blueprint")] APIBlueprint,
      Blade,
      CSS,
      [Description("Closure Templates")] ClosureTemplates,
      EJS,
      HTML,
      [Description("HTML+Django")] HTMLDjango,
      [Description("HTML+ECR")] HTMLECR,
      [Description("HTML+ERB")] HTMLERB,
      [Description("HTML+EEX")] HTMLEEX,
      [Description("HTML+PHP")] HTMLPHP,
      Haml,
      Handlebars,
      [Description("Jupyter Notebook")] JupyterNotebook,
      Kit,
      Latte,
      Less,
      Liquid,
      MTML,
      Marko,
      Mask,
      Pic,
      PostScript,
      Pug,
      RAML,
      RHTML,
      RUNOFF,
      SCSS,
      Sass,
      Scaml,
      Slim,
      Stylus,
      TeX,
      Tea,
      Twig,
      Vue,
    }
  }
}
