// Decompiled with JetBrains decompiler
// Type: Microsoft.VisualStudio.Telemetry.SensitiveDataScrubber.CredScanDataScrubber
// Assembly: Microsoft.VisualStudio.Telemetry, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 0E58FD5B-7E43-40D6-A963-E92D0F67BACC
// Assembly location: C:\Program Files\Azure DevOps Server 2022\Application Tier\Web Services\bin\Microsoft.VisualStudio.Telemetry.dll

using System.Text.RegularExpressions;

namespace Microsoft.VisualStudio.Telemetry.SensitiveDataScrubber
{
  internal sealed class CredScanDataScrubber : ISensitiveDataScrubber
  {
    private const string FILE_SYSTEM_PROVIDER = "(\\$ansible_vault\\W|tokencache\\W|(?-i)MII(?i)|(?-i)eyJ(?i)|secret[a-z]{0,10}[0-9]?\\W|password\\W|key\\W|(?-i)zCa(?i)|(?-i)\\+ASt(?i)|(?-i)((user|abc)@123|T!T@n|P0rsche|[Pp][@a]ss@?w[0o]rd[^a-rt-z\\uFFFD\\u0000-\\u0019]|homer?rocks|coMmac|iis6!dfu|!!123ab|Pa55word|p1ter|WS2012R2R0cks|DSFS0319Test|March2010M2|mCertPwd|\\$erver|#Bugsfor|ITG2Install|TitanPwd|ChocoCheese|Micr0s0ft|test1test|tieorg|homerocks|IWantYouToTripLikeIDo|UL0brlXlp_r8vG6iiRvCcsFDfu6bJ6KK|Tdh3Klrec4dJbOyONDOkCQ84BWN1JN|Y29NbWFjITEy|elvis1|S_MSLocal|n1130@T!T)(?i)|pa?[s\\$]*wo?r?d[^a-rt-z\\ufffd\\u0000-\\u0019]|pw[:=\\s]|(?-i)gh[pousr]_(?i)|(?-i)xox[pbarose](?i)|dapi\\W|token[a-z]{0,10}[0-9]?\\W|\\-p[:\\s=]|azurecr\\W|(?-i)AIza(?i)|[a-z0-9/\\+]{43}=|pat\\W|ado\\W|vsts\\W|azuredevops\\W|visualstudio\\.com\\W|dev\\.azure\\.com\\W|microsoft\\.maps\\W|sig=|code=|botframework\\W|virtualearth\\W|api/maps\\W|userpass\\W|credentials\\W|cmdkey\\W|authenti\\W|sign_in\\W|db_|://[^/:\\s]{2,64}:|login\\W|authorization\\W|net(\\.exe)? use\\W|credential\\W|schtasks\\W|/u:|winexe\\W|\\-u[:\\s=]|auth\\W|securestring\\W|snmp\\W|certutil\\W|zdbg\\W|vsts_token\\W|curl\\W|powershell[\\s\\.]|ps1|\\-u(ser)?[:\\s=]|smc\\W|autologon\\W|ldifde\\W|rclone\\W|\\-\\-env\\W|signtool\\W|net[\\s\\.\\u0022\\u0027]|x509c\\W|connectionstring\\W|sas\\W)";
    private const string FULL_TEXT_PROVIDER = "(?i)(\\$ansible_vault\\W|tokencache\\W|(?-i)MII(?i)|(?-i)eyJ(?i)|secret[a-z]{0,10}[0-9]?\\W|password\\W|key\\W|(?-i)zCa(?i)|(?-i)\\+ASt(?i)|(?-i)((user|abc)@123|T!T@n|P0rsche|[Pp][@a]ss@?w[0o]rd[^a-rt-z\\uFFFD\\u0000-\\u0019]|homer?rocks|coMmac|iis6!dfu|!!123ab|Pa55word|p1ter|WS2012R2R0cks|DSFS0319Test|March2010M2|mCertPwd|\\$erver|#Bugsfor|ITG2Install|TitanPwd|ChocoCheese|Micr0s0ft|test1test|tieorg|homerocks|IWantYouToTripLikeIDo|UL0brlXlp_r8vG6iiRvCcsFDfu6bJ6KK|Tdh3Klrec4dJbOyONDOkCQ84BWN1JN|Y29NbWFjITEy|elvis1|S_MSLocal|n1130@T!T)(?i)|pa?[s\\$]*wo?r?d[^a-rt-z\\ufffd\\u0000-\\u0019]|pw[:=\\s]|(?-i)gh[pousr]_(?i)|(?-i)xox[pbarose](?i)|dapi\\W|token[a-z]{0,10}[0-9]?\\W|\\-p[:\\s=]|azurecr\\W|(?-i)AIza(?i)|[a-z0-9/\\+]{43}=|pat\\W|ado\\W|vsts\\W|azuredevops\\W|visualstudio\\.com\\W|dev\\.azure\\.com\\W|microsoft\\.maps\\W|sig=|code=|botframework\\W|virtualearth\\W|api/maps\\W|userpass\\W|credentials\\W|cmdkey\\W|authenti\\W|sign_in\\W|db_|://[^/:\\s]{2,64}:|login\\W|authorization\\W|net(\\.exe)? use\\W|credential\\W|schtasks\\W|/u:|winexe\\W|\\-u[:\\s=]|auth\\W|securestring\\W|snmp\\W|certutil\\W|zdbg\\W|vsts_token\\W|curl\\W|powershell[\\s\\.]|ps1|\\-u(ser)?[:\\s=]|smc\\W|autologon\\W|ldifde\\W|rclone\\W|\\-\\-env\\W|signtool\\W|net[\\s\\.\"']|x509c\\W|connectionstring\\W|sas\\W)";
    private static readonly Regex FileSystemProviderRegex = new Regex("(\\$ansible_vault\\W|tokencache\\W|(?-i)MII(?i)|(?-i)eyJ(?i)|secret[a-z]{0,10}[0-9]?\\W|password\\W|key\\W|(?-i)zCa(?i)|(?-i)\\+ASt(?i)|(?-i)((user|abc)@123|T!T@n|P0rsche|[Pp][@a]ss@?w[0o]rd[^a-rt-z\\uFFFD\\u0000-\\u0019]|homer?rocks|coMmac|iis6!dfu|!!123ab|Pa55word|p1ter|WS2012R2R0cks|DSFS0319Test|March2010M2|mCertPwd|\\$erver|#Bugsfor|ITG2Install|TitanPwd|ChocoCheese|Micr0s0ft|test1test|tieorg|homerocks|IWantYouToTripLikeIDo|UL0brlXlp_r8vG6iiRvCcsFDfu6bJ6KK|Tdh3Klrec4dJbOyONDOkCQ84BWN1JN|Y29NbWFjITEy|elvis1|S_MSLocal|n1130@T!T)(?i)|pa?[s\\$]*wo?r?d[^a-rt-z\\ufffd\\u0000-\\u0019]|pw[:=\\s]|(?-i)gh[pousr]_(?i)|(?-i)xox[pbarose](?i)|dapi\\W|token[a-z]{0,10}[0-9]?\\W|\\-p[:\\s=]|azurecr\\W|(?-i)AIza(?i)|[a-z0-9/\\+]{43}=|pat\\W|ado\\W|vsts\\W|azuredevops\\W|visualstudio\\.com\\W|dev\\.azure\\.com\\W|microsoft\\.maps\\W|sig=|code=|botframework\\W|virtualearth\\W|api/maps\\W|userpass\\W|credentials\\W|cmdkey\\W|authenti\\W|sign_in\\W|db_|://[^/:\\s]{2,64}:|login\\W|authorization\\W|net(\\.exe)? use\\W|credential\\W|schtasks\\W|/u:|winexe\\W|\\-u[:\\s=]|auth\\W|securestring\\W|snmp\\W|certutil\\W|zdbg\\W|vsts_token\\W|curl\\W|powershell[\\s\\.]|ps1|\\-u(ser)?[:\\s=]|smc\\W|autologon\\W|ldifde\\W|rclone\\W|\\-\\-env\\W|signtool\\W|net[\\s\\.\\u0022\\u0027]|x509c\\W|connectionstring\\W|sas\\W)");
    private static readonly Regex FullTextProviderRegex = new Regex("(?i)(\\$ansible_vault\\W|tokencache\\W|(?-i)MII(?i)|(?-i)eyJ(?i)|secret[a-z]{0,10}[0-9]?\\W|password\\W|key\\W|(?-i)zCa(?i)|(?-i)\\+ASt(?i)|(?-i)((user|abc)@123|T!T@n|P0rsche|[Pp][@a]ss@?w[0o]rd[^a-rt-z\\uFFFD\\u0000-\\u0019]|homer?rocks|coMmac|iis6!dfu|!!123ab|Pa55word|p1ter|WS2012R2R0cks|DSFS0319Test|March2010M2|mCertPwd|\\$erver|#Bugsfor|ITG2Install|TitanPwd|ChocoCheese|Micr0s0ft|test1test|tieorg|homerocks|IWantYouToTripLikeIDo|UL0brlXlp_r8vG6iiRvCcsFDfu6bJ6KK|Tdh3Klrec4dJbOyONDOkCQ84BWN1JN|Y29NbWFjITEy|elvis1|S_MSLocal|n1130@T!T)(?i)|pa?[s\\$]*wo?r?d[^a-rt-z\\ufffd\\u0000-\\u0019]|pw[:=\\s]|(?-i)gh[pousr]_(?i)|(?-i)xox[pbarose](?i)|dapi\\W|token[a-z]{0,10}[0-9]?\\W|\\-p[:\\s=]|azurecr\\W|(?-i)AIza(?i)|[a-z0-9/\\+]{43}=|pat\\W|ado\\W|vsts\\W|azuredevops\\W|visualstudio\\.com\\W|dev\\.azure\\.com\\W|microsoft\\.maps\\W|sig=|code=|botframework\\W|virtualearth\\W|api/maps\\W|userpass\\W|credentials\\W|cmdkey\\W|authenti\\W|sign_in\\W|db_|://[^/:\\s]{2,64}:|login\\W|authorization\\W|net(\\.exe)? use\\W|credential\\W|schtasks\\W|/u:|winexe\\W|\\-u[:\\s=]|auth\\W|securestring\\W|snmp\\W|certutil\\W|zdbg\\W|vsts_token\\W|curl\\W|powershell[\\s\\.]|ps1|\\-u(ser)?[:\\s=]|smc\\W|autologon\\W|ldifde\\W|rclone\\W|\\-\\-env\\W|signtool\\W|net[\\s\\.\"']|x509c\\W|connectionstring\\W|sas\\W)");

    public bool ContainsSensitiveData(string propertyValue, bool scrubAllTypesOfPersonalData = false) => CredScanDataScrubber.FileSystemProviderRegex.IsMatch(propertyValue) || CredScanDataScrubber.FullTextProviderRegex.IsMatch(propertyValue);
  }
}
