// Decompiled with JetBrains decompiler
// Type: Microsoft.Azure.Storage.Shared.Protocol.Constants
// Assembly: Microsoft.Azure.Storage.Common, Version=11.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// MVID: 0978DA65-6954-4A99-9ACB-2EF3D979A5D5
// Assembly location: C:\Program Files\Azure DevOps Server 2022\Application Tier\Web Services\bin\Microsoft.Azure.Storage.Common.dll

using System;
using System.Globalization;

namespace Microsoft.Azure.Storage.Shared.Protocol
{
  public static class Constants
  {
    public const int MaxParallelOperationThreadCount = 64;
    public const int MaxSharedAccessPolicyIdentifiers = 5;
    public const int DefaultWriteBlockSizeBytes = 4194304;
    public const int DefaultSubStreamBufferSize = 4194304;
    public const long DefaultParallelDownloadRangeSizeBytes = 16777216;
    public const long MaxSingleUploadBlobSize = 268435456;
    public const int MaxBlockSize = 104857600;
    public const int MaxAppendBlockSize = 4194304;
    public const int MaxIdleTimeMs = 120000;
    public const int MaxRangeGetContentMD5Size = 4194304;
    public const int MaxRangeGetContentCRC64Size = 4194304;
    public const long MaxBlockNumber = 50000;
    public const long MaxBlobSize = 5242880000000;
    public const int MinLargeBlockSize = 4194305;
    public const int MaxRetainedVersionsPerBlob = 10;
    public const int MaxSubOperationPerBatch = 256;
    public static readonly TimeSpan MaxMaximumExecutionTime = TimeSpan.FromDays(24.0);
    public static readonly TimeSpan DefaultClientSideTimeout = TimeSpan.FromMinutes(5.0);
    public static readonly TimeSpan MaximumRetryBackoff = TimeSpan.FromHours(1.0);
    public static readonly TimeSpan MaximumAllowedTimeout = TimeSpan.FromSeconds((double) int.MaxValue);
    public static readonly TimeSpan DefaultNetworkTimeout = TimeSpan.FromSeconds(100.0);
    internal static readonly int MaximumAllowedRetentionDays = 365;
    internal const int DefaultBufferSize = 65536;
    internal const string LogSourceName = "Microsoft.Azure.Storage";
    public const int PageSize = 512;
    public const long KB = 1024;
    public const long MB = 1048576;
    public const long GB = 1073741824;
    public const string AES256 = "AES256";
    public const string CommittedBlocksElement = "CommittedBlocks";
    public const string UncommittedBlocksElement = "UncommittedBlocks";
    public const string BlockElement = "Block";
    public const string NameElement = "Name";
    public const string SizeElement = "Size";
    public const string BlockListElement = "BlockList";
    public const string MessagesElement = "QueueMessagesList";
    public const string MessageElement = "QueueMessage";
    public const string MessageIdElement = "MessageId";
    public const string InsertionTimeElement = "InsertionTime";
    public const string ExpirationTimeElement = "ExpirationTime";
    public const string PopReceiptElement = "PopReceipt";
    public const string TimeNextVisibleElement = "TimeNextVisible";
    public const string MessageTextElement = "MessageText";
    public const string DequeueCountElement = "DequeueCount";
    public const string PageRangeElement = "PageRange";
    public const string ClearRangeElement = "ClearRange";
    public const string PageListElement = "PageList";
    public const string StartElement = "Start";
    public const string EndElement = "End";
    public const string HandleIdElement = "HandleId";
    public const string PathElement = "Path";
    public const string ClientIpElement = "ClientIp";
    public const string OpenTimeElement = "OpenTime";
    public const string LastReconnectTimeElement = "LastReconnectTime";
    public const string FileIdElement = "FileId";
    public const string ParentIdElement = "ParentId";
    public const string SessionIdElement = "SessionId";
    public const string DelimiterElement = "Delimiter";
    public const string BlobPrefixElement = "BlobPrefix";
    public const string CacheControlElement = "Cache-Control";
    public const string ContentTypeElement = "Content-Type";
    public const string ContentEncodingElement = "Content-Encoding";
    public const string ContentLanguageElement = "Content-Language";
    public const string ContentLengthElement = "Content-Length";
    public const string ContentMD5Element = "Content-MD5";
    internal const string ContentCRC64Element = "Content-CRC64";
    public const string EnumerationResultsElement = "EnumerationResults";
    public const string ServiceEndpointElement = "ServiceEndpoint";
    public const string ContainerNameElement = "ContainerName";
    public const string ShareNameElement = "ShareName";
    public const string DirectoryPathElement = "DirectoryPath";
    public const string BlobsElement = "Blobs";
    public const string PrefixElement = "Prefix";
    public const string MaxResultsElement = "MaxResults";
    public const string MarkerElement = "Marker";
    public const string NextMarkerElement = "NextMarker";
    public const string EtagElement = "Etag";
    public const string CreationTimeElement = "Creation-Time";
    public const string LastModifiedElement = "Last-Modified";
    public const string ServerEncryptionElement = "ServerEncrypted";
    public const string UrlElement = "Url";
    public const string BlobElement = "Blob";
    public const string CopyIdElement = "CopyId";
    public const string CopyStatusElement = "CopyStatus";
    public const string CopySourceElement = "CopySource";
    public const string CopyProgressElement = "CopyProgress";
    public const string CopyCompletionTimeElement = "CopyCompletionTime";
    public const string CopyStatusDescriptionElement = "CopyStatusDescription";
    public const string IncrementalCopy = "IncrementalCopy";
    public const string CopyDestinationSnapshotElement = "CopyDestinationSnapshot";
    public const string DeletedElement = "Deleted";
    public const string DeletedTimeElement = "DeletedTime";
    public const string RemainingRetentionDaysElement = "RemainingRetentionDays";
    public const string EncryptionScopeElement = "EncryptionScope";
    public const string PageBlobValue = "PageBlob";
    public const string BlockBlobValue = "BlockBlob";
    public const string AppendBlobValue = "AppendBlob";
    public const string LockedValue = "locked";
    public const string UnlockedValue = "unlocked";
    public const string LeaseAvailableValue = "available";
    public const string LeasedValue = "leased";
    public const string LeaseExpiredValue = "expired";
    public const string LeaseBreakingValue = "breaking";
    public const string LeaseBrokenValue = "broken";
    public const string LeaseInfiniteValue = "infinite";
    public const string LeaseFixedValue = "fixed";
    public const int MinimumBreakLeasePeriod = 0;
    public const int MaximumBreakLeasePeriod = 60;
    public const int MinimumLeaseDuration = 15;
    public const int MaximumLeaseDuration = 60;
    public const string CopyPendingValue = "pending";
    public const string CopySuccessValue = "success";
    public const string CopyAbortedValue = "aborted";
    public const string CopyFailedValue = "failed";
    public const string RehydratePendingToHot = "rehydrate-pending-to-hot";
    public const string RehydratePendingToCool = "rehydrate-pending-to-cool";
    public const string GeoUnavailableValue = "unavailable";
    public const string GeoLiveValue = "live";
    public const string GeoBootstrapValue = "bootstrap";
    public const string AccessTierElement = "AccessTier";
    public const string AccessTierInferred = "AccessTierInferred";
    public const string AccessTierChangeTimeElement = "AccessTierChangeTime";
    public const string ArchiveStatusElement = "ArchiveStatus";
    public const string BlobTypeElement = "BlobType";
    public const string HasImmutabilityPolicyElement = "HasImmutabilityPolicy";
    public const string HasLegalHoldElement = "HasLegalHold";
    public const string LeaseStatusElement = "LeaseStatus";
    public const string LeaseStateElement = "LeaseState";
    public const string LeaseDurationElement = "LeaseDuration";
    public const string PublicAccessElement = "PublicAccess";
    public const string SnapshotElement = "Snapshot";
    public const string ContainersElement = "Containers";
    public const string ContainerElement = "Container";
    public const string SharesElement = "Shares";
    public const string ShareElement = "Share";
    public const string QuotaElement = "Quota";
    public const string FileRangeElement = "Range";
    public const string FileRangeListElement = "Ranges";
    public const string HandleElement = "Handle";
    public const string FileHandleListElement = "HandleList";
    public const string EntriesElement = "Entries";
    public const string FileElement = "File";
    public const string FileDirectoryElement = "Directory";
    public const string QueuesElement = "Queues";
    public const string QueueNameElement = "Name";
    public const string QueueElement = "Queue";
    public const string PropertiesElement = "Properties";
    public const string MetadataElement = "Metadata";
    public const string InvalidMetadataName = "x-ms-invalid-name";
    public const string MaxResults = "MaxResults";
    public const string CommittedElement = "Committed";
    public const string UncommittedElement = "Uncommitted";
    public const string LatestElement = "Latest";
    public const string SignedIdentifiers = "SignedIdentifiers";
    public const string SignedIdentifier = "SignedIdentifier";
    public const string AccessPolicy = "AccessPolicy";
    public const string Id = "Id";
    public const string Start = "Start";
    public const string Expiry = "Expiry";
    public const string KeyInfo = "KeyInfo";
    public const string UserDelegationKey = "UserDelegationKey";
    public const string SignedOid = "SignedOid";
    public const string SignedTid = "SignedTid";
    public const string SignedStart = "SignedStart";
    public const string SignedExpiry = "SignedExpiry";
    public const string SignedVersion = "SignedVersion";
    public const string SignedService = "SignedService";
    public const string Value = "Value";
    internal const string DateTimeFormatter = "yyyy-MM-ddTHH:mm:ssK";
    public const string Permission = "Permission";
    public const string Messages = "messages";
    internal const string ErrorException = "exceptiondetails";
    public const string ErrorRootElement = "Error";
    public const string ErrorCode = "Code";
    internal const string ErrorCodePreview = "code";
    public const string ErrorMessage = "Message";
    internal const string ErrorMessagePreview = "message";
    public const string ErrorExceptionMessage = "ExceptionMessage";
    public const string ErrorExceptionStackTrace = "StackTrace";
    internal const string EdmEntityTypeNamespaceName = "AzureTableStorage";
    internal const string EdmEntityTypeName = "DefaultContainer";
    internal const string EntitySetName = "Tables";
    internal const string Edm = "Edm.";
    internal const string DefaultNamespaceName = "account";
    internal const string DefaultTableName = "TableName";
    internal const string XMLAcceptHeaderValue = "application/xml";
    internal const string JsonLightAcceptHeaderValue = "application/json;odata=minimalmetadata";
    internal const string JsonFullMetadataAcceptHeaderValue = "application/json;odata=fullmetadata";
    internal const string JsonNoMetadataAcceptHeaderValue = "application/json;odata=nometadata";
    internal const string NoMetadata = "odata=nometadata";
    internal const string JsonContentTypeHeaderValue = "application/json";
    internal const string ETagPrefix = "\"datetime'";
    internal const string OdataTypeString = "@odata.type";
    internal const string EdmBinary = "Edm.Binary";
    internal const string EdmBoolean = "Emd.Boolean";
    internal const string EdmDateTime = "Edm.DateTime";
    internal const string EdmDouble = "Edm.Double";
    internal const string EdmGuid = "Edm.Guid";
    internal const string EdmInt32 = "Edm.Int32";
    internal const string EdmInt64 = "Edm.Int64";
    internal const string EdmString = "Edm.String";
    internal const string BatchBoundaryMarker = "multipart/mixed; boundary=batch_";
    internal const string ChangesetBoundaryMarker = "Content-Type: multipart/mixed; boundary=changeset_";
    internal const string BatchPrefix = "batch_";
    internal const string ChangesetSeparator = "--changeset_";
    internal const string ContentTypeApplicationHttp = "Content-Type: application/http";
    internal const string ContentTransferEncodingBinary = "Content-Transfer-Encoding: binary";
    internal const string ContentID = "Content-ID: ";
    internal const string ContentTypeApplicationJson = "Content-Type: application/json";
    internal const string HTTP1_1 = "HTTP/1.1";

    public static class HeaderConstants
    {
      public static readonly string UserAgent;
      public static readonly string UserAgentComment = string.Format((IFormatProvider) CultureInfo.InvariantCulture, "(.NET Core; {0} {1})", (object) Environment.OSVersion.Platform, (object) Environment.OSVersion.Version);
      public const string UserAgentProductName = "Azure-Storage";
      public const string UserAgentProductVersion = "11.2.3";
      public const string PrefixForStorageHeader = "x-ms-";
      public const string TrueHeader = "true";
      public const string FalseHeader = "false";
      public const string PrefixForStorageProperties = "x-ms-prop-";
      public const string PrefixForStorageMetadata = "x-ms-meta-";
      public const string ContentDispositionResponseHeader = "Content-Disposition";
      public const string ContentLengthHeader = "Content-Length";
      public const string ContentLanguageHeader = "Content-Language";
      public const string CreationTimeHeader = "x-ms-creation-time";
      public const string EtagHeader = "ETag";
      public const string HasImmutabilityPolicyHeader = "x-ms-has-immutability-policy";
      public const string HasLegalHoldHeader = "x-ms-has-legal-hold";
      public const string ServerEncrypted = "x-ms-server-encrypted";
      public const string EncryptionScopeHeader = "x-ms-encryption-scope";
      public const string DefaultEncryptionScopeHeader = "x-ms-default-encryption-scope";
      public const string PreventEncryptionScopeOverrideHeader = "x-ms-deny-encryption-scope-override";
      public const string ServerRequestEncrypted = "x-ms-request-server-encrypted";
      public const string RangeHeader = "x-ms-range";
      public const string RangeContentMD5Header = "x-ms-range-get-content-md5";
      public const string RangeContentCRC64Header = "x-ms-range-get-content-crc64";
      public const string ContentCrc64Header = "x-ms-content-crc64";
      public const string StorageVersionHeader = "x-ms-version";
      public const string CopySourceHeader = "x-ms-copy-source";
      public const string RequiresSyncHeader = "x-ms-requires-sync";
      public const string SourceRangeHeader = "x-ms-source-range";
      public const string SourceIfMatchHeader = "x-ms-source-if-match";
      public const string SourceIfMatchCrcHeader = "x-ms-source-if-match-crc64";
      public const string SourceIfModifiedSinceHeader = "x-ms-source-if-modified-since";
      public const string SourceIfNoneMatchHeader = "x-ms-source-if-none-match";
      public const string SourceIfNoneMatchCrcHeader = "x-ms-source-if-none-match-crc64";
      public const string SourceIfUnmodifiedSinceHeader = "x-ms-source-if-unmodified-since";
      public const string FileType = "x-ms-type";
      public const string FileCacheControlHeader = "x-ms-cache-control";
      public const string FileContentDispositionRequestHeader = "x-ms-content-disposition";
      public const string FileContentEncodingHeader = "x-ms-content-encoding";
      public const string FileContentLanguageHeader = "x-ms-content-language";
      public const string FileContentMD5Header = "x-ms-content-md5";
      public const string FileContentCRC64Header = "x-ms-content-crc64";
      public const string SourceContentMD5Header = "x-ms-source-content-md5";
      internal const string SourceContentCRC64Header = "x-ms-source-content-crc64";
      public const string FileContentTypeHeader = "x-ms-content-type";
      public const string FileContentLengthHeader = "x-ms-content-length";
      public const string FileRangeWrite = "x-ms-write";
      public const string BlobType = "x-ms-blob-type";
      public const string SnapshotHeader = "x-ms-snapshot";
      public const string DeleteSnapshotHeader = "x-ms-delete-snapshots";
      public const string AccessTierHeader = "x-ms-access-tier";
      public const string ArchiveStatusHeader = "x-ms-archive-status";
      public const string AccessTierInferredHeader = "x-ms-access-tier-inferred";
      public const string AccessTierChangeTimeHeader = "x-ms-access-tier-change-time";
      public const string BlobCacheControlHeader = "x-ms-blob-cache-control";
      public const string BlobContentDispositionRequestHeader = "x-ms-blob-content-disposition";
      public const string BlobContentEncodingHeader = "x-ms-blob-content-encoding";
      public const string BlobContentLanguageHeader = "x-ms-blob-content-language";
      public const string BlobContentMD5Header = "x-ms-blob-content-md5";
      internal const string BlobContentCRC64Header = "x-ms-blob-content-crc64";
      public const string BlobContentTypeHeader = "x-ms-blob-content-type";
      public const string BlobContentLengthHeader = "x-ms-blob-content-length";
      public const string BlobSequenceNumber = "x-ms-blob-sequence-number";
      public const string SequenceNumberAction = "x-ms-sequence-number-action";
      public const string BlobCommittedBlockCount = "x-ms-blob-committed-block-count";
      public const string BlobAppendOffset = "x-ms-blob-append-offset";
      public const string IfSequenceNumberLEHeader = "x-ms-if-sequence-number-le";
      public const string IfSequenceNumberLTHeader = "x-ms-if-sequence-number-lt";
      public const string IfSequenceNumberEqHeader = "x-ms-if-sequence-number-eq";
      public const string IfMaxSizeLessThanOrEqualHeader = "x-ms-blob-condition-maxsize";
      public const string IfAppendPositionEqualHeader = "x-ms-blob-condition-appendpos";
      public const string LeaseIdHeader = "x-ms-lease-id";
      public const string LeaseStatus = "x-ms-lease-status";
      public const string LeaseState = "x-ms-lease-state";
      public const string PageWrite = "x-ms-page-write";
      public const string ApproximateMessagesCount = "x-ms-approximate-messages-count";
      public const string Date = "x-ms-date";
      public const string RequestIdHeader = "x-ms-request-id";
      public const string ClientRequestIdHeader = "x-ms-client-request-id";
      public const string BlobPublicAccess = "x-ms-blob-public-access";
      public const string FilePermission = "x-ms-file-permission";
      public const string FilePermissionCopyMode = "x-ms-file-permission-copy-mode";
      public const string FileCopyFromSource = "source";
      public const string FileCopyOverride = "override";
      public const string FilePermissionInherit = "Inherit";
      public const string FilePermissionKey = "x-ms-file-permission-key";
      public const string FileAttributes = "x-ms-file-attributes";
      public const string FileCopySetArchive = "x-ms-file-copy-set-archive";
      public const string FileCopyInoreReadOnly = "x-ms-file-copy-ignore-readonly";
      public const string FileAttributesNone = "None";
      public const string FileCreationTime = "x-ms-file-creation-time";
      public const string FileLastWriteTime = "x-ms-file-last-write-time";
      public const string FileChangeTime = "x-ms-file-change-time";
      public const string FileTimeNow = "Now";
      public const string Preserve = "Preserve";
      public const string FileId = "x-ms-file-id";
      public const string FileParentId = "x-ms-file-parent-id";
      public const string RehydratePriorityHeader = "x-ms-rehydrate-priority";
      public const string RangeHeaderFormat = "bytes={0}-{1}";
      public const string TargetStorageVersion = "2019-07-07";
      public const string File = "File";
      public const string AllFileHandles = "*";
      public const string HandleId = "x-ms-handle-id";
      public const string NumHandlesClosed = "x-ms-number-of-handles-closed";
      public const string PageBlob = "PageBlob";
      public const string BlockBlob = "BlockBlob";
      public const string AppendBlob = "AppendBlob";
      public const string SnapshotsOnlyValue = "only";
      public const string IncludeSnapshotsValue = "include";
      public const string PopReceipt = "x-ms-popreceipt";
      public const string NextVisibleTime = "x-ms-time-next-visible";
      public const string PeekOnly = "peekonly";
      public const string ContainerPublicAccessType = "x-ms-blob-public-access";
      public const string LeaseActionHeader = "x-ms-lease-action";
      public const string ProposedLeaseIdHeader = "x-ms-proposed-lease-id";
      public const string LeaseDurationHeader = "x-ms-lease-duration";
      public const string LeaseBreakPeriodHeader = "x-ms-lease-break-period";
      public const string LeaseTimeHeader = "x-ms-lease-time";
      public const string KeyNameHeader = "x-ms-key-name";
      public const string CopyIdHeader = "x-ms-copy-id";
      public const string CopyCompletionTimeHeader = "x-ms-copy-completion-time";
      public const string CopyStatusHeader = "x-ms-copy-status";
      public const string CopyProgressHeader = "x-ms-copy-progress";
      public const string CopyDescriptionHeader = "x-ms-copy-status-description";
      public const string CopyActionHeader = "x-ms-copy-action";
      public const string CopyTypeHeader = "x-ms-copy-type";
      public const string CopyActionAbort = "abort";
      public const string IncrementalCopyHeader = "x-ms-incremental-copy";
      public const string CopyDestinationSnapshotHeader = "x-ms-copy-destination-snapshot";
      public const string ShareSize = "x-ms-share-size";
      public const string ShareQuota = "x-ms-share-quota";
      public const string Recursive = "x-ms-recursive";
      public const string Marker = "x-ms-marker";
      public const string ClientProvidedEncryptionSuccess = "x-ms-request-server-encrypted";
      public const string ClientProvidedEncyptionKey = "x-ms-encryption-key";
      public const string ClientProvidedEncyptionKeyHash = "x-ms-encryption-key-sha256";
      public const string ClientProvidedEncyptionAlgorithm = "x-ms-encryption-algorithm";
      public const string ClientProvidedEncyptionKeySource = "x-ms-source-encryption-key";
      public const string ClientProvidedEncyptionKeyHashSource = "x-ms-source-encryption-key-sha256";
      public const string ClientProvidedEncyptionKeyAlgorithmSource = "x-ms-source-encryption-algorithm";
      internal const string SkuNameName = "x-ms-sku-name";
      internal const string AccountKindName = "x-ms-account-kind";
      internal const string PayloadAcceptHeader = "Accept";
      internal const string PayloadContentTypeHeader = "Content-Type";
      internal const string AcceptCharset = "Accept-Charset";
      internal const string AcceptCharsetValue = "UTF-8";
      internal const string PostTunnelling = "X-HTTP-Method";
      internal const string IfMatch = "If-Match";
      internal const string Prefer = "Prefer";
      internal const string PreferReturnContent = "return-content";
      internal const string PreferReturnNoContent = "return-no-content";
      internal const string StorageErrorCodeHeader = "x-ms-error-code";

      static HeaderConstants() => Constants.HeaderConstants.UserAgent = "Azure-Storage/11.2.3 " + Constants.HeaderConstants.UserAgentComment;
    }

    public static class QueryConstants
    {
      public const string Snapshot = "snapshot";
      public const string ShareSnapshot = "sharesnapshot";
      public const string SignedStart = "st";
      public const string SignedExpiry = "se";
      public const string SignedResource = "sr";
      public const string BlobResourceType = "b";
      public const string BlobSnapshotResourceType = "bs";
      public const string ContainerResourceType = "c";
      public const string SignedKeyOid = "skoid";
      public const string SignedKeyTid = "sktid";
      public const string SignedKeyStart = "skt";
      public const string SignedKeyExpiry = "ske";
      public const string SignedKeyService = "sks";
      public const string SignedKeyVersion = "skv";
      public const string SignedResourceTypes = "srt";
      public const string SignedServices = "ss";
      public const string SignedProtocols = "spr";
      public const string SignedIP = "sip";
      public const string SasTableName = "tn";
      public const string SignedPermissions = "sp";
      public const string StartPartitionKey = "spk";
      public const string StartRowKey = "srk";
      public const string EndPartitionKey = "epk";
      public const string EndRowKey = "erk";
      public const string SignedIdentifier = "si";
      public const string SignedKey = "sk";
      public const string SignedVersion = "sv";
      public const string Signature = "sig";
      public const string CacheControl = "rscc";
      public const string ContentType = "rsct";
      public const string ContentEncoding = "rsce";
      public const string ContentLanguage = "rscl";
      public const string ContentDisposition = "rscd";
      public const string ApiVersion = "api-version";
      public const string MessageTimeToLive = "messagettl";
      public const string VisibilityTimeout = "visibilitytimeout";
      public const string NumOfMessages = "numofmessages";
      public const string PopReceipt = "popreceipt";
      public const string ResourceType = "restype";
      public const string Component = "comp";
      public const string CopyId = "copyid";
      public const string Marker = "marker";
    }

    public static class ContinuationConstants
    {
      public const string ContinuationTopElement = "ContinuationToken";
      public const string NextMarkerElement = "NextMarker";
      public const string NextPartitionKeyElement = "NextPartitionKey";
      public const string NextRowKeyElement = "NextRowKey";
      public const string NextTableNameElement = "NextTableName";
      public const string TargetLocationElement = "TargetLocation";
      public const string VersionElement = "Version";
      public const string CurrentVersion = "2.0";
      public const string TypeElement = "Type";
      public const string BlobType = "Blob";
      public const string QueueType = "Queue";
      public const string TableType = "Table";
      public const string FileType = "File";
    }

    public static class VersionConstants
    {
      public const string August2013 = "2013-08-15";
      public const string February2012 = "2012-02-12";
    }

    public static class AnalyticsConstants
    {
      public const string LogsContainer = "$logs";
      public const string MetricsCapacityBlob = "$MetricsCapacityBlob";
      public const string MetricsHourPrimaryTransactionsBlob = "$MetricsHourPrimaryTransactionsBlob";
      public const string MetricsHourPrimaryTransactionsTable = "$MetricsHourPrimaryTransactionsTable";
      public const string MetricsHourPrimaryTransactionsQueue = "$MetricsHourPrimaryTransactionsQueue";
      public const string MetricsHourPrimaryTransactionsFile = "$MetricsHourPrimaryTransactionsFile";
      public const string MetricsMinutePrimaryTransactionsBlob = "$MetricsMinutePrimaryTransactionsBlob";
      public const string MetricsMinutePrimaryTransactionsTable = "$MetricsMinutePrimaryTransactionsTable";
      public const string MetricsMinutePrimaryTransactionsQueue = "$MetricsMinutePrimaryTransactionsQueue";
      public const string MetricsMinutePrimaryTransactionsFile = "$MetricsMinutePrimaryTransactionsFile";
      public const string MetricsHourSecondaryTransactionsBlob = "$MetricsHourSecondaryTransactionsBlob";
      public const string MetricsHourSecondaryTransactionsTable = "$MetricsHourSecondaryTransactionsTable";
      public const string MetricsHourSecondaryTransactionsQueue = "$MetricsHourSecondaryTransactionsQueue";
      public const string MetricsHourSecondaryTransactionsFile = "$MetricsHourSecondaryTransactionsFile";
      public const string MetricsMinuteSecondaryTransactionsBlob = "$MetricsMinuteSecondaryTransactionsBlob";
      public const string MetricsMinuteSecondaryTransactionsTable = "$MetricsMinuteSecondaryTransactionsTable";
      public const string MetricsMinuteSecondaryTransactionsQueue = "$MetricsMinuteSecondaryTransactionsQueue";
      public const string MetricsMinuteSecondaryTransactionsFile = "$MetricsMinuteSecondaryTransactionsFile";
      public const string LoggingVersionV1 = "1.0";
      public const string MetricsVersionV1 = "1.0";
    }

    public static class EncryptionConstants
    {
      internal const string EncryptionProtocolV1 = "1.0";
      internal const string KeyWrappingIV = "KeyWrappingIV";
      public const string BlobEncryptionData = "encryptiondata";
      public const string TableEncryptionKeyDetails = "_ClientEncryptionMetadata1";
      public const string TableEncryptionPropertyDetails = "_ClientEncryptionMetadata2";
      public const string AgentMetadataKey = "EncryptionLibrary";
      public const string AgentMetadataValue = ".NET 11.2.3";
    }
  }
}
