IF NOT EXISTS (
      SELECT * FROM sys.database_principals
      WHERE NAME = 'VSODIAGROLE')
BEGIN
      CREATE ROLE VSODIAGROLE AUTHORIZATION dbo
END

EXEC sp_addrolemember 'db_datareader', 'VSODIAGROLE'

GRANT VIEW DATABASE STATE TO VSODIAGROLE
GRANT SHOWPLAN TO VSODIAGROLE
GRANT VIEW DEFINITION TO VSODIAGROLE
