// Decompiled with JetBrains decompiler
// Type: Microsoft.VisualStudio.Services.Search.Shared.Platform.Primitives.Telemetry.SearchIndexerTelemetryEvents
// Assembly: Microsoft.VisualStudio.Services.Search.Shared.Platform.Primitives.Telemetry, Version=19.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 4AA9C920-1627-4C01-9F3D-849A7BC9C916
// Assembly location: C:\Program Files\Azure DevOps Server 2022\Application Tier\Web Services\bin\Plugins\Microsoft.VisualStudio.Services.Search.Shared.Platform.Primitives.Telemetry.dll

using System.Collections.Generic;

namespace Microsoft.VisualStudio.Services.Search.Shared.Platform.Primitives.Telemetry
{
  public static class SearchIndexerTelemetryEvents
  {
    public const string IndexingEventName = "TFS/Search/Indexing";
    public static readonly IDictionary<string, string> PropertyToEventMap = (IDictionary<string, string>) new Dictionary<string, string>()
    {
      {
        "CorrelationId",
        "TFS.Search.Indexing.CorrelationId"
      },
      {
        "CollectionId",
        "TFS.Search.Indexing.CollectionId"
      },
      {
        "ProjectId",
        "TFS.Search.Indexing.ProjectId"
      },
      {
        "RepositoryId",
        "TFS.Search.Indexing.RepositoryId"
      },
      {
        "RepositoryIndexingUnitId",
        "TFS.Search.Indexing.RepositoryIndexingUnitId"
      },
      {
        "ProjectIndexingUnitId",
        "TFS.Search.Indexing.ProjectIndexingUnitId"
      },
      {
        "ChangeType",
        "TFS.Search.Indexing.ChangeType"
      },
      {
        "EntityType",
        "TFS.Search.Indexing.EntityType"
      },
      {
        "IndexingUnitType",
        "TFS.Search.Indexing.IndexingUnitType"
      },
      {
        "BulkIndexing",
        "TFS.Search.Indexing.BulkIndexing"
      },
      {
        "ContinuousIndexing",
        "TFS.Search.Indexing.ContinuousIndexing"
      },
      {
        "JobName",
        "TFS.Search.Indexing.JobName"
      },
      {
        "AttemptCount",
        "TFS.Search.Indexing.AttemptCount"
      },
      {
        "JobExecutionTime",
        "TFS.Search.Indexing.JobExecutionTime"
      },
      {
        "OperationStatus",
        "TFS.Search.Indexing.OperationStatus"
      },
      {
        "JobExecutionResultMessage",
        "TFS.Search.Indexing.JobExecutionResultMessage"
      },
      {
        "E2ETimeInSeconds",
        "TFS.Search.Indexing.E2ETimeInSeconds"
      },
      {
        "JobYieldCount",
        "TFS.Search.Indexing.JobYieldCount"
      },
      {
        "ItemsProcessedAcrossJobYields",
        "TFS.Search.Indexing.ItemsProcessedAcrossJobYields"
      },
      {
        "SearchExtensionInstallSubscriberInvoke",
        "TFS.Search.Indexing.SearchExtensionInstallSubscriberInvoke"
      },
      {
        "SearchExtensionUninstallSubscriberInvoke",
        "TFS.Search.Indexing.SearchExtensionUninstallSubscriberInvoke"
      },
      {
        "SearchExtensionInstallSubscriberFailure",
        "TFS.Search.Indexing.SearchExtensionInstallSubscriberFailure"
      },
      {
        "SearchExtensionUninstallSubscriberFailure",
        "TFS.Search.Indexing.SearchExtensionUninstallSubscriberFailure"
      },
      {
        "SearchExtensionAccountFaultInJobTrigger",
        "TFS.Search.Indexing.SearchExtensionAccountFaultInJobTrigger"
      },
      {
        "NoOfItemsCrawled",
        "TFS.Search.Indexing.NoOfItemsCrawled"
      },
      {
        "TotalItemsCrawled",
        "TFS.Search.Indexing.TotalItemsCrawled"
      },
      {
        "NumberOfTempStoreRecords",
        "TFS.Search.Indexing.NumberOfTempStoreRecords"
      },
      {
        "CrawlerServiceFailure",
        "TFS.Search.Indexing.CrawlerServiceFailure"
      },
      {
        "CrawlerServiceFailureReason",
        "TFS.Search.Indexing.CrawlerServiceFailureReason"
      },
      {
        "CrawlingTime",
        "TFS.Search.Indexing.CrawlingTime"
      },
      {
        "NumberOfFilesFailedToCrawl",
        "TFS.Search.Indexing.NumberOfFilesFailedToCrawl"
      },
      {
        "NumberOfUniqueFilesCrawled",
        "TFS.Search.Indexing.NumberOfUniqueFilesCrawled"
      },
      {
        "SizeOfSupportedCrawledItems",
        "TFS.Search.Indexing.SizeOfSupportedCrawledItems"
      },
      {
        "NumberOfSkippedUnSupportedFiles",
        "TFS.Search.Indexing.NumberOfSkippedUnSupportedFiles"
      },
      {
        "NumberOfSkippedFilesWithUnsupportedExtension",
        "TFS.Search.Indexing.NumberOfSkippedFilesWithUnsupportedExtension"
      },
      {
        "NumberOfSkippedFilesDueToExcludedFolder",
        "TFS.Search.Indexing.NumberOfSkippedFilesDueToExcludedFolder"
      },
      {
        "NumberOfWorkItemRevisionsCrawled",
        "TFS.Search.Indexing.NumberOfWorkItemRevisionsCrawled"
      },
      {
        "NumberOfWorkItemDiscussionsCrawled",
        "TFS.Search.Indexing.NumberOfWorkItemDiscussionsCrawled"
      },
      {
        "BranchName",
        "TFS.Search.Indexing.BranchName"
      },
      {
        "BaseCommitId",
        "TFS.Search.Indexing.BaseCommitId"
      },
      {
        "TargetCommitId",
        "TFS.Search.Indexing.TargetCommitId"
      },
      {
        "NoOfGetMetaDataCalls",
        "TFS.Search.Indexing.NoOfGetMetaDataCalls"
      },
      {
        "TotalNoOfMetaDataSeeds",
        "TFS.Search.Indexing.TotalNoOfMetaDataSeeds"
      },
      {
        "TotalTfvcBranchesInProject",
        "TFS.Search.Indexing.TotalTfvcBranchesInProject"
      },
      {
        "TotalTfvcBranchesRemovedDueToExcludedFolderPaths",
        "TFS.Search.Indexing.TotalTfvcBranchesRemovedDueToExcludedFolderPaths"
      },
      {
        "TotalTfvcBranchesGroupedViaFolderPath",
        "TFS.Search.Indexing.TotalTfvcBranchesGroupedViaFolderPath"
      },
      {
        "TotalGroupsRemovedWithSingleTfvcBranch",
        "TFS.Search.Indexing.TotalGroupsRemovedWithSingleTfvcBranch"
      },
      {
        "TfvcBranchGroupSplitCountDueToUpperCapOnParallelBranchesToCrawl",
        "TFS.Search.Indexing.TfvcBranchGroupSplitCountDueToUpperCapOnParallelBranchesToCrawl"
      },
      {
        "TfvcBranchGroupsThatExceededUpperCapOnParallelBranchesToCrawl",
        "TFS.Search.Indexing.TfvcBranchGroupsThatExceededUpperCapOnParallelBranchesToCrawl"
      },
      {
        "MaxPotentialTfvcBranchCountInGroup",
        "TFS.Search.Indexing.MaxPotentialTfvcBranchCountInGroup"
      },
      {
        "TimeTakenInSecByTfvcGetBranches",
        "TFS.Search.Indexing.TimeTakenInSecByTfvcGetBranches"
      },
      {
        "TotalTfvcBranchGroups",
        "TFS.Search.Indexing.TotalTfvcBranchGroups"
      },
      {
        "TfvcBranchGroupIdToBranchesCount",
        "TFS.Search.Indexing.TfvcBranchGroupIdToBranchesCount"
      },
      {
        "ParserServiceFailure",
        "TFS.Search.Indexing.ParserServiceFailure"
      },
      {
        "ParserServiceFailureReason",
        "TFS.Search.Indexing.ParserServiceFailureReason"
      },
      {
        "ParsingTime",
        "TFS.Search.Indexing.ParsingTime"
      },
      {
        "NoOfFilesParsed",
        "TFS.Search.Indexing.NoOfFilesParsed"
      },
      {
        "NoOfFilesFailedToParsed",
        "TFS.Search.Indexing.NoOfFilesFailedToParsed"
      },
      {
        "FeederServiceFailure",
        "TFS.Search.Indexing.FeederServiceFailure"
      },
      {
        "FeederServiceFailureReason",
        "TFS.Search.Indexing.FeederServiceFailureReason"
      },
      {
        "FeederServiceESFailureReason",
        "TFS.Search.Indexing.FeederServiceESFailureReason"
      },
      {
        "FeedingTime",
        "TFS.Search.Indexing.FeedingTime"
      },
      {
        "NoOfItemsFedToES",
        "TFS.Search.Indexing.NoOfItemsFedToES"
      },
      {
        "NoOfItemsAcceptedByES",
        "TFS.Search.Indexing.NoOfItemsAcceptedByES"
      },
      {
        "NoOfItemsFailed",
        "TFS.Search.Indexing.NoOfItemsFailed"
      },
      {
        "ESBulkIndexingTime",
        "TFS.Search.Indexing.ESBulkIndexingTime"
      },
      {
        "ESBulkDeleteByQueryTime",
        "TFS.Search.Indexing.ESBulkDeleteByQueryTime"
      },
      {
        "ESFailedBulkDeleteByQueryTime",
        "TFS.Search.Indexing.ESFailedBulkDeleteByQueryTime"
      },
      {
        "ESDocsPendingScroll",
        "TFS.Search.Indexing.ESDocsPendingScroll"
      },
      {
        "TotalNumberOfItemsFailedToIndex",
        "TFS.Search.Indexing.TotalNumberOfItemsFailedToIndex"
      },
      {
        "TotalNumberOfFailedItemsReIndexedSuccessfully",
        "TFS.Search.Indexing.TotalNumberOfFailedItemsReIndexedSuccessfully"
      },
      {
        "TotalNumberOfFailedItemsExceedingRetryLimit",
        "TFS.Search.Indexing.TotalNumberOfFailedItemsExceedingRetryLimit"
      }
    };
    private const string IndexingBaseName = "TFS.Search.Indexing.";

    public static ICollection<string> GetAdditiveProperties() => (ICollection<string>) new HashSet<string>()
    {
      "NoOfItemsCrawled",
      "NumberOfFilesFailedToCrawl",
      "NumberOfUniqueFilesCrawled",
      "SizeOfSupportedCrawledItems",
      "NumberOfSkippedUnSupportedFiles",
      "NumberOfSkippedFilesWithUnsupportedExtension",
      "NumberOfSkippedFilesDueToExcludedFolder",
      "NumberOfWorkItemRevisionsCrawled",
      "NumberOfWorkItemDiscussionsCrawled",
      "NoOfGetMetaDataCalls",
      "NumberOfTempStoreRecords",
      "TotalItemsCrawled",
      "ParsingTime",
      "NoOfFilesParsed",
      "NoOfFilesFailedToParsed",
      "FeedingTime",
      "NoOfItemsFedToES",
      "NoOfItemsFailed",
      "NoOfItemsAcceptedByES",
      "TotalNumberOfItemsFailedToIndex",
      "TotalNumberOfFailedItemsExceedingRetryLimit",
      "ESBulkIndexingTime",
      "ESBulkDeleteByQueryTime",
      "ESFailedBulkDeleteByQueryTime"
    };
  }
}
