using System;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Extension]
[assembly: SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames", Justification = "Assembly not deployed outside of Microsoft, no strong name required.")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.IncidentChangeRequestResult.#IncidentChanges", Justification = "Serializable class")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.Incident.#Relationship", Justification = "Serializable class")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Overaged", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.NotificationStatus.#Overaged")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.AzureAd.Icm.Types.ArgumentCheck.Throw(System.String,System.String)", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.AlertSourceIncident.#ThrowIfNotValid(Microsoft.AzureAd.Icm.Types.AlertSourceIncident)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "DescriptionEntry", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.AlertSourceIncident.#ThrowIfNotValid(Microsoft.AzureAd.Icm.Types.AlertSourceIncident)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.MitigationProviderJobStatus.#ResultDetails")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.RuleFilter.#FilterProperties", Justification = "Serializable class")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.RotationEntry.#OnCallContacts", Justification = "Serializable class")]
[assembly: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.RotationEntry.#OnCallContacts")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "Microsoft.AzureAd.Icm.Types.TeamType")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.PagedResult`1.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.PagedResult`1.#Result")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.PageToken.#Token")]
[assembly: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.PagedResult`1.#.ctor(System.Collections.Generic.List`1<!0>)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Microsoft.AzureAd.Icm.Types.IcmConstants+ResourceAccess+Status")]
[assembly: SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope = "type", Target = "Microsoft.AzureAd.Icm.Types.IcmConstants+ResourceAccess+Provider")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Microsoft.AzureAd.Icm.Types.IcmConstants+ResourceAccess+Provider")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Mins", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.IcmConstants+Misc.#IncidentChangesMaxOwnershipMins")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "Microsoft.AzureAd.Icm.Types.TeamSelectionOption")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.PirResponseTimeline.#Equals(System.Object)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Desc", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.AimsConnector.AimsIncidentWrapper.#AlertDesc")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Datacenter", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.AimsConnector.AimsIncidentWrapper.#Datacenter")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Microsoft.AzureAd.Icm.Types.AimsConnector")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.RotationContacts.#ContactIds")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.RotationShift.#RotationList")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.RotationShiftConfig.#RotationShifts")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Pm", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.IcmConstants+Dates.#AmPmHourFormat")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Microsoft.AzureAd.Icm.Types.IcmConstants+OnCall+ParameterNames")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Microsoft.AzureAd.Icm.Types.IcmConstants+OnCall")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Microsoft.AzureAd.Icm.Types.IcmConstants+OnCall+Constants")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.IcmConstants+HtmlTags.#AllowedTags")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.ContactsRootSerializable.#Contacts")]
[assembly: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.FieldValidator.#ValidateUrl(System.String,System.String,System.Collections.Generic.IDictionary`2<System.String,Microsoft.AzureAd.Icm.Types.InvalidReasons>)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.AzureAd.Icm.Types.ContactsRootSerializable.#Contacts")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyProduct("IcmTypes")]
[assembly: AssemblyTrademark("")]
[assembly: Guid("8ccf35ab-76e9-4d28-a69e-6f875b2ebdc4")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyCopyright("Copyright © Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyDescription("EngSys-OneIM-Libraries-IcmV2Public master (342fb5a) Microsoft Azure®")]
[assembly: AssemblyTitle("Microsoft.AzureAd.Icm.Types")]
[assembly: AssemblyFileVersion("2.1.10.37")]
[assembly: AssemblyVersion("2.1.0.0")]
