// Decompiled with JetBrains decompiler
// Type: Microsoft.OData.InternalErrorCodes
// Assembly: Microsoft.TeamFoundation.OData.Core, Version=7.6.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 6619C7F6-E44A-4143-AE77-6D570F968D9A
// Assembly location: C:\Program Files\Azure DevOps Server 2022\Application Tier\Web Services\bin\Microsoft.TeamFoundation.OData.Core.dll

namespace Microsoft.OData
{
  internal enum InternalErrorCodes
  {
    ODataWriterCore_WriteEnd_UnreachableCodePath,
    ODataWriterCore_ValidateTransition_UnreachableCodePath,
    ODataWriterCore_Scope_Create_UnreachableCodePath,
    ODataWriterCore_PropertyAndAnnotationCollector,
    ODataWriterCore_ParentNestedResourceInfoScope,
    ODataUtils_VersionString_UnreachableCodePath,
    ODataUtilsInternal_IsPayloadKindSupported_UnreachableCodePath,
    ODataUtils_GetDefaultEncoding_UnreachableCodePath,
    ODataMessageWriter_WriteProperty,
    ODataMessageWriter_WriteEntityReferenceLink,
    ODataMessageWriter_WriteEntityReferenceLinks,
    ODataMessageWriter_WriteError,
    ODataMessageWriter_WriteServiceDocument,
    ODataMessageWriter_WriteMetadataDocument,
    ODataCollectionWriter_CreateCollectionWriter_UnreachableCodePath,
    ODataCollectionWriterCore_ValidateTransition_UnreachableCodePath,
    ODataCollectionWriterCore_WriteEnd_UnreachableCodePath,
    ODataParameterWriter_CannotCreateParameterWriterForFormat,
    ODataParameterWriterCore_ValidateTransition_InvalidTransitionFromStart,
    ODataParameterWriterCore_ValidateTransition_InvalidTransitionFromCanWriteParameter,
    ODataParameterWriterCore_ValidateTransition_InvalidTransitionFromActiveSubWriter,
    ODataParameterWriterCore_ValidateTransition_InvalidTransitionFromCompleted,
    ODataParameterWriterCore_ValidateTransition_InvalidTransitionFromError,
    ODataParameterWriterCore_ValidateTransition_UnreachableCodePath,
    ODataParameterWriterCore_WriteEndImplementation_UnreachableCodePath,
    QueryPathValidator_ValidateSegment_Root,
    QueryPathValidator_ValidateSegment_NonRoot,
    ODataBatchWriter_ValidateTransition_UnreachableCodePath,
    ODataBatchWriterUtils_HttpMethod_ToText_UnreachableCodePath,
    ODataBatchReader_ReadImplementation,
    ODataBatchReader_GetEndBoundary_Completed,
    ODataBatchReader_GetEndBoundary_Exception,
    ODataBatchReader_GetEndBoundary_UnknownValue,
    ODataBatchReaderStream_SkipToBoundary,
    ODataBatchReaderStream_ReadLine,
    ODataBatchReaderStream_ReadWithDelimiter,
    ODataBatchReaderStreamBuffer_ScanForBoundary,
    ODataBatchReaderStreamBuffer_ReadWithLength,
    JsonReader_Read,
    ODataReader_CreateReader_UnreachableCodePath,
    ODataReaderCore_ReadImplementation,
    ODataReaderCoreAsync_ReadAsynchronously,
    ODataCollectionReader_CreateReader_UnreachableCodePath,
    ODataCollectionReaderCore_ReadImplementation,
    ODataCollectionReaderCoreAsync_ReadAsynchronously,
    ODataParameterReaderCore_ReadImplementation,
    ODataParameterReaderCoreAsync_ReadAsynchronously,
    ODataParameterReaderCore_ValueMustBePrimitiveOrNull,
    ODataRawValueUtils_ConvertStringToPrimitive,
    EdmCoreModel_PrimitiveType,
    ReaderValidationUtils_ResolveAndValidateTypeName_Strict_TypeKind,
    ReaderValidationUtils_ResolveAndValidateTypeName_Lax_TypeKind,
    ODataMetadataFormat_CreateOutputContextAsync,
    ODataMetadataFormat_CreateInputContextAsync,
    ODataModelFunctions_UnsupportedMethodOrProperty,
    ODataJsonLightPropertyAndValueDeserializer_ReadPropertyValue,
    ODataJsonLightPropertyAndValueDeserializer_GetNonEntityValueKind,
    ODataJsonLightReader_ReadResourceStart,
    ODataJsonLightResourceDeserializer_ReadTopLevelResourceSetAnnotations,
    ODataJsonLightCollectionDeserializer_ReadCollectionStart,
    ODataJsonLightCollectionDeserializer_ReadCollectionStart_TypeKindFromPayloadFunc,
    ODataJsonLightCollectionDeserializer_ReadCollectionEnd,
    ODataJsonLightEntityReferenceLinkDeserializer_ReadSingleEntityReferenceLink,
    ODataJsonLightEntityReferenceLinkDeserializer_ReadEntityReferenceLinksAnnotations,
    ODataJsonLightParameterDeserializer_ReadNextParameter,
    EdmTypeWriterResolver_GetReturnTypeForOperationImportGroup,
    ODataVersionCache_UnknownVersion,
  }
}
